<?php

$servername = "localhost";
$username = "root";
$password = "";
$dbname = "anaya"; 
// $base_url="://localhost:8081/asmakgroup/"
$connF = mysqli_connect($servername,$username,$password,$dbname);

if($connF)
{
    echo "";
}
else
{
    echo "connection failed";
}


function generateRandomPassword(){
	
	$combination = 'qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM0123456789~!@#$%^&*()_+[]{}<>?';
	$combination = str_shuffle($combination);
	$randomPassword = substr($combination,0,8);
	return $randomPassword;
}

function sentConfirmMail($email,$name,$cCode){
	
	//PHPMailer Function
			$mail = new PHPMailer;
			$mail->isSMTP();
			$mail->SMTPDebug = 0;
			$mail->Debugoutput = 'html';
			$mail->Host = 'smtp.gmail.com';
			$mail->Port = 587;
			$mail->SMTPSecure = 'tls';
			$mail->SMTPAuth = true;
			$mail->Username = "mailer.nilkamal@gmail.com";
			$mail->Password = "nilkamal@123456";
			$mail->setFrom('mailer.nilkamal@gmail.com', 'nilkamal Support');
			$mail->addAddress($email, $name);
			$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
			$mail->Subject = 'Please Confirm Your nilkamal Account';
			$mail->Body = "
						<p>Hi! $name </p>
						<p>Thank you for registering on our site </p>
						<br><br><br>
						<b> Please visit My Account page on site to confirm your email </b>
						<br><br>
						Your nilkamal Account Confirmation Code:&nbsp; <strong>$cCode</strong>
						<br><br>
						<b><i>Important! Please verifiy your email just after logged into the site</i></b>
						";
			if (!$mail->send()) {
    			echo "<script>alert('Somthing Wrong! Please Contact Us')</script>";
			}
	
}


function recoverPassword(){
	
	global $connF;
	global $wrongpass;
	
	if(isset($_POST['recoverpass'])){
		
		$customerEmail = $_POST['cus_email'];
		
		//Google Recaptcha
		$sKey = "6LdScHYUAAAAAL6_FSP4Jgmv_Vd4-2sYytWiBt0K";
		$gResponse = $_POST['g-recaptcha-response'];
		$remoteIP = $_SERVER['REMOTE_ADDR'];
		$guRL = "s://www.google.com/recaptcha/api/siteverify?secret=$sKey&response=$gResponse&remoteip=$remoteIP";
		$retuenResponse = file_get_contents($guRL);
		$jsonResponse = json_decode($retuenResponse);
		
		$getCustomerSql = "SELECT * FROM customer WHERE cusEmail='$customerEmail'";
		$getCustomer = mysqli_query($connF,$getCustomerSql);
		$getCustomerRow = mysqli_fetch_array($getCustomer);
		$getCustomerCount = mysqli_num_rows($getCustomer);
		
		if($getCustomerCount > 0 || $jsonResponse->success){
			
			$randomPassword = generateRandomPassword();
			$encRandomPassword = md5($randomPassword);
			
			$setRandowPasswordSql = "UPDATE customer SET cusPassword='$encRandomPassword' WHERE cusEmail='$customerEmail'";
			$setRandowPassword = mysqli_query($connF,$setRandowPasswordSql);
			$customerName = $getCustomerRow['cusName'];


			//PHPMailer Function
			$mail = new PHPMailer;
			$mail->isSMTP();
			$mail->SMTPDebug = 0;
			$mail->Debugoutput = 'html';
			$mail->Host = 'smtp.gmail.com';
			$mail->Port = 587;
			$mail->SMTPSecure = 'tls';
			$mail->SMTPAuth = true;
			$mail->Username = "mailer.nilkamal@gmail.com";
			$mail->Password = "nilkamal@123456";
			$mail->setFrom('mailer.nilkamal@gmail.com', 'nilkamal Support');
			$mail->addAddress($customerEmail, $customerName);
			$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
			$mail->Subject = 'Your nilkamal Account Password';
			$mail->Body = "
						<b> This password is generated by nilkamal Servers </b>
						<br><br>
						Your nilkamal Account Password:&nbsp; <strong>$randomPassword</strong>
						<br><br>
						<b><i>Important! Please change your password just after logged into the site</i></b>
						";
			if (!$mail->send()) {
    			$wrongpass = "Somthing Wrong";
			} 
			else {
   				$wrongpass = "Password has been sent your email! Please check your inbox/spam folder";
			}
		}
		else{
			if(!$getCustomerCount>0){
				$wrongpass = "Email not found, Please check your email";
			}
			$wrongpass = "Please complete the Recaptcha!";
		}
	}
	
	
}

function setGetCookie(){
	
	global $random; 
	$random= rand(0, 9999999); 
	if(!isset($_COOKIE['user_cookie'])) {
    	setcookie('user_cookie',$random, time() + (86400), "/");//86400 = 1 day
	}
	else {
    	return $_COOKIE['user_cookie']; 
	}
	
}

function switchLoginLogout(){
	if(!isset($_SESSION['cusEmail'])){
		echo "<li><a href='register.php'>Register</a></li>";
		echo "<li><a href='login.php'>Login</a></li>";
	}else{
		echo "<li><a href='customers/myaccount.php?myorders'>My Account</a></li>";
		echo "<li><a href='logout.php'>Logout</a></li>";
	}
}

function switchLoginLogout1(){
	if(!isset($_SESSION['cusEmail'])){
		echo "<li class='nav-item dnone'><a href='register.php' class='nav-link'><span class='icon-user-plus' style='font-size: 24px; padding-right: 7px' data-toggle='tooltip' title='Login'></span><span class='dnone'>Register</span></a></li>";
echo "<li class='nav-item dnone'><a href='login.php' class='nav-link'><span class='icon-key' style='font-size: 24px; padding-right: 7px' data-toggle='tooltip' title='Login'></span><span class='dnone'>Login</a></li>";
		
	}else{
		echo "
<li class='nav-item dnone'><a href='customers/myaccount.php?myorders' class='nav-link'><span class='icon-folder' style='font-size: 24px; padding-right: 7px' data-toggle='tooltip' title='My Account'></span><span class='dnone'>My Account</span></a></li>"
		;
		echo "<li class='nav-item dnone'><a href='logout.php' class='nav-link'>Logout</a></li>";
	}
}


function changePassword(){
	
	global $connF;
	
	if(isset($_POST['changepassword'])){
		$currentUser = $_SESSION['cusEmail'];
		$getCustomerPasswordSql = "SELECT * FROM customer WHERE cusEmail='$currentUser'";
		$getCustomerPassword = mysqli_query($connF,$getCustomerPasswordSql);	
		$getCustomerPasswordRow = mysqli_fetch_array($getCustomerPassword);
		
		$currentPassword = $_POST['current_pass'];
		$newPassword = $_POST['new_pass'];
		$cNewPassword = $_POST['new_cpass'];
		
		$currentPasswordDB = $getCustomerPasswordRow['cusPassword'];
		$decryptCurrentPassword = md5($currentPasswordDB);
		
		if($currentPassword == $decryptCurrentPassword && $newPassword == $cNewPassword){
			$encryptNewPassword = md5($newPassword);
			$changePasswordSql = "UPDATE customer SET cusPassword='$encryptNewPassword' WHERE cusEmail = '$currentUser'";
			$changePassword = mysqli_query($connF,$changePasswordSql);
			echo "<script>alert('Password changed successfully!, Please login to contiune')</script>";
			session_destroy();
			echo "<script>window.open('../login.php','_self')</script>";
		}
		else if($currentPasswordDB != $currentPassword && $newPassword == $cNewPassword){
			
			echo "<script>alert('Your current password is wrong!')</script>";
		}
		else if($currentPasswordDB == $currentPassword && $newPassword != $cNewPassword){
			
			echo "<script>alert('Confirm password mismatch')</script>";
		}
		else{
			echo "<script>alert('Something wrong!')</script>";
		}
			
	}
}



function getAdminDetails(){
	
	global $connF;
	
	$currentAdmin = $_SESSION['email'];
	$adminDetailsSql = "SELECT * FROM admin WHERE adminEmail ='$currentAdmin'";
	$adminDetails = mysqli_query($connF,$adminDetailsSql);
	$adminDetailsRow = mysqli_fetch_array($adminDetails);
	
	$adminName = $adminDetailsRow['adminName'];
	echo "$adminName";	
}



//Start Add Admin Details


function addNewAdmin(){
	global $connF;
	if(isset($_POST['addnewadmin'])){
		$adminName = $_POST['adminName'];
		$adminEmail = $_POST['adminEmail'];
		$adminPass = $_POST['adminPass'];
		$adminCPass = $_POST['adminCPass'];
		$adminImg = $_FILES['adminimg1']['name'];
		$adminTempImg = $_FILES['adminimg1']['tmp_name'];
		$adminPno = $_POST['adminPNo'];
		
		if($adminPass == $adminCPass){
			$adminPassEnc = md5($adminPass);
			$addAdminSql = "INSERT INTO admin(adminName, adminEmail, adminPassword, adminPhoto, adminPNum) VALUES ('$adminName','$adminEmail','$adminPassEnc','$adminImg','$adminPno')";
			$addAdmin = mysqli_query($connF,$addAdminSql);
			move_uploaded_file($adminTempImg,"resources/admin_img/$adminImg");
			if($addAdmin){
			echo "<script>alert('Admin Added')</script>";
			echo "<script>window.open('index.php?addadmin','_self')</script>";
		}
		}
	}
}
// End Add Admin Details


// Start Admin View

function viewAdmin(){
	global $connF;
	$viewAdminSql ="SELECT * FROM admin WHERE 1";
	$viewAdmin = mysqli_query($connF,$viewAdminSql);
	
	while($viewAdminRow = mysqli_fetch_array($viewAdmin)){
		$adminId = $viewAdminRow['adminId'];
		$adminName = $viewAdminRow['adminName'];
		$adminEmail = $viewAdminRow['adminEmail'];
		$adminPass = $viewAdminRow['adminPassword'];
		$adminPassDec = md5($adminPass);
		$adminImg = $viewAdminRow['adminPhoto'];
		$adminPno = $viewAdminRow['adminPNum'];
		
		echo "	
				<tr>
					<td>$adminId</td>
					<td>$adminName</td>
					<td>$adminEmail</td>
					<td>$adminPassDec</td>
					<td><img src='resources/admin_img/$adminImg' style='width: 50px;height:50px;'></td>
					<td>$adminPno</td>
					<td><a href='index.php?deleteAdmin=$adminId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
				</tr>
		
			";
	}
}

// End View Admin

// Start Delete Admin

function deleteAdmin(){
	global $connF;
	if(isset($_GET['deleteAdmin'])){
		$adminId = $_GET['deleteAdmin'];
		$deleteAdminSql = "DELETE FROM admin WHERE adminId='$adminId'";
		$deleteAdmin = mysqli_query($connF,$deleteAdminSql);
		if($deleteAdmin){
			echo"<script>alert('Admin Deleted')</script>";
			echo "<script>window.open('index.php?addadmin','_self')</script>";
		}
	}
}
// End Delete Admin

// Start Add Project Category

function addProjectCategory(){
    global $connF;
    if(isset($_POST['addnewprojectcategory'])){
        
        $projectCatName = $_POST['projectCatName'];

        // Check if the file has been uploaded
        if (isset($_FILES['projectCatImg']) && $_FILES['projectCatImg']['error'] === UPLOAD_ERR_OK) {
            $projectCatImg = $_FILES['projectCatImg']['name'];
            $tempImg1 = $_FILES['projectCatImg']['tmp_name'];
            
            // Move the uploaded file
            if (move_uploaded_file($tempImg1, "resources/projectcategory_img/$projectCatImg")) {
                
                // Insert the data into the database
                $addProjectCatSql = "INSERT INTO projectcategory(projectCatName, projectCatImg) VALUES ('$projectCatName','$projectCatImg')";
                $addProjectCat = mysqli_query($connF, $addProjectCatSql);
                
                if($addProjectCat){
                    echo "<script>alert('Project Category Added')</script>";
                    echo "<script>window.open('index.php?addprojectcategory','_self')</script>";
                } else {
                    echo "<script>alert('Database error: Project Category not added')</script>";
                }
            } else {
                echo "<script>alert('Failed to upload the image.')</script>";
            }
        } else {
            echo "<script>alert('No file uploaded or file upload error.')</script>";
        }
    }
}

// End Add Project Category

// Start View Project Category


function ViewProjectCat(){
	global $connF;
	$getProjectCatSql = "SELECT * FROM projectcategory WHERE 1";
	$getProjectCat = mysqli_query($connF,$getProjectCatSql);
	while($getProjectCatRow = mysqli_fetch_array($getProjectCat)){

		$projectCatId = $getProjectCatRow['projectCatId'];
		$projectCatImg = $getProjectCatRow['projectCatImg'];
        $projectCatName = $getProjectCatRow['projectCatName'];
		
		echo "
			<tr>
				<td>$projectCatId</td>
				<td>$projectCatName</td>
                
				<td><img src='resources/projectcategory_img/$projectCatImg' style='width: 50px;height:50px;'></td>
				"; echo"
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteProjectCat=$projectCatId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>			
				<td><a href='index.php?editprojectcategory=$projectCatId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";
	}
}
// End View Project Category

// Start Edit Project Category
function editprojectcat() {
	global $connF;

	if(isset($_POST['editprojectcat'])){
		$projectCatId = $_GET['editprojectcategory'];
			
		$getprojectCatSql = "SELECT * FROM projectcategory WHERE projectCatId='$projectCatId'";
		$getprojectCat = mysqli_query($connF,$getprojectCatSql);
		$getprojectCatRow = mysqli_fetch_array($getprojectCat);

		$projectCatName = $_POST['projectCatName'];
		$projectCatImg=$_POST['projectCatImg'];
		$projectCatImgOld = $getprojectCatRow['projectCatImg'];
		
		$projectCatImg = $_FILES['projectCatImg']['name'];
		
		if(empty($projectCatImg)){
			$projectCatImg = $projectCatImgOld;
		}
		$tempImg1 = $_FILES['projectCatImg']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/projectcategory_img/$projectCatImg");
		
		$updateProjectCatSql = "UPDATE projectcategory SET projectCatName='$projectCatName', projectCatImg='$projectCatImg' WHERE projectCatId='$projectCatId'";
		$updateProjectCat = mysqli_query($connF, $updateProjectCatSql);

		if($updateProjectCat){
			echo "<script>alert('Project Updated');</script>";
			echo "<script>window.open('index.php?addprojectcategory','_self');</script>";
		} else {
			echo "<script>alert('Something went wrong!');</script>";
			echo "<script>window.open('index.php?addprojectcategory','_self');</script>";
		}
	}
}

// End Edit Project Category

// Start Delete Project Category

function deleteProjectCat(){
	global $connF;
	if(isset($_GET['deleteProjectCat'])){
		
		$projectCatId = $_GET['deleteProjectCat'];
		$deleteProjectCatSql = "DELETE FROM  projectcategory WHERE projectCatId='$projectCatId'";
		$deleteProjectCat = mysqli_query($connF,$deleteProjectCatSql);
		if($deleteProjectCat){
			echo "<script>window.open('index.php?addprojectcategory','_self')</script>";
		}
	}
	
}
// End Project Category

// Start Add Project
function addProject(){
	global $connF;
	if(isset($_POST['addnewproject'])){
		
		$projectName = $_POST['projectName'];
		$projectCatId = $_POST['projectCatId'];
		$projectstatusId = $_POST['projectstatusId'];
		$projectDesc = $_POST['projectDesc'];
		$projectImg = $_FILES['projectImg']['name'];
		$tempImg1 = $_FILES['projectImg']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/project_img/$projectImg");

		$addProjectSql = "INSERT INTO project(projectName,projectImg,projectDesc,projectCatId,projectstatusId) VALUES ('$projectName','$projectImg','$projectDesc','$projectCatId'.'$projectstatusId')";
		$addProject = mysqli_query($connF,$addProjectSql);
		if($addProject){
			echo "<script>alert('Project Added')</script>";
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}
		
	}
}

// End Add Project

// Start Edit Project
function updateProject(){
	
	global $connF;
	
	if(isset($_POST['editproject'])){
		
		$projectId = $_GET['editproject'];
		
		$getProjectSql = "SELECT * FROM project WHERE projectId='$projectId'";
		$getProject = mysqli_query($connF,$getProjectSql);
		$getProjectRow = mysqli_fetch_array($getProject);
		
		$projectName = $_POST['projectName'];
		$projectImg = $_FILES['projectImg']['name'];

		$projectDesc = $_POST['projectDesc'];
		$projectCatId=$_POST['projectCatId'];
		$projectstatusId=$_POST['projectstatusId'];
		$projectImgOld = $getProjectRow['projectImg'];

		
		if(empty($projectImg)){
			$projectImg = $projectImgOld;
		}
		$tempImg1 = $_FILES['projectImg']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/project_img/$projectImg");

        $updateProjectSql = "UPDATE project SET projectName='$projectName',projectImg='$projectImg',projectDesc='$projectDesc',projectCatId='$projectCatId',projectstatusId='$projectstatusId' WHERE projectId='$projectId'";
		$updateProject = mysqli_query($connF,$updateProjectSql);
		if($updateProject){
			echo "<script>alert('Project Updated')</script>";
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}
	    }
	}
// End Edit Project

//Start View Project
function displayProject(){
	global $connF;
	$getProjectSql = "SELECT * FROM project WHERE 1";
	$getProject = mysqli_query($connF,$getProjectSql);
	while($getProjectRow = mysqli_fetch_array($getProject)){
		$projectId = $getProjectRow['projectId'];
		$projectName = $getProjectRow['projectName'];
		$projectImg = $getProjectRow['projectImg'];
		$projectDesc = $getProjectRow['projectDesc'];
		$projectCatId = $getProjectRow['projectCatId'];
		$getprojectCatNameSql = "SELECT * FROM projectcategory WHERE projectCatId='$projectCatId'";
		$getprojectCatName = mysqli_query($connF,$getprojectCatNameSql);
		$getprojectCatNameRow = mysqli_fetch_array($getprojectCatName);
		$projectCatName = $getprojectCatNameRow['projectCatName'];

		$projectstatusId = $getProjectRow['projectstatusId'];
		$projectstatusSql = "SELECT * FROM projectstatus WHERE projectstatusId='$projectstatusId'";
		$getprojectstatus = mysqli_query($connF,$projectstatusSql);
		$getprojectstatusRow = mysqli_fetch_array($getprojectstatus);
		$projectstatus = $getprojectstatusRow['projectstatus'];
		echo "
			<tr>
				<td>$projectId</td>
				<td>$projectName</td>
				<td>$projectDesc</td>
			<td><img src='resources/project_img/$projectImg' style='width: 50px;height:50px;'></td>

				<td>$projectCatName</td>
				<td>$projectstatus</td>
				<td><a href='index.php?editproject=$projectId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>
		<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteProject=$projectId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>

			</tr>
		
		";

	}
}

// End View Project 

// Start Delete Project
function deleteProject(){
	global $connF;
	if(isset($_GET['deleteProject'])){
		
		$ProjectId = $_GET['deleteProject'];
		$deleteProjectSql = "DELETE FROM project WHERE projectId='$ProjectId'";
		$deleteProject = mysqli_query($connF,$deleteProjectSql);
		if($deleteProject){
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}
	}
	
}
// End Delete Project

// Count Project Status Id 1

function countUpcoming(){
	
	global $connF;
	$getUpcomingDetailSql = "SELECT * FROM project WHERE projectstatusId=1";
	$getUpcomingDetail = mysqli_query($connF,$getUpcomingDetailSql);
	$UpcomingCount = mysqli_num_rows($getUpcomingDetail);
	
	echo "$UpcomingCount";
}
function countOngoing(){
	
	global $connF;
	$getOngoingDetailSql = "SELECT * FROM project WHERE projectstatusId=2";
	$getOngoingDetail = mysqli_query($connF,$getOngoingDetailSql);
	$OngoingCount = mysqli_num_rows($getOngoingDetail);
	
	echo "$OngoingCount";
}

function countCompleted(){
	
	global $connF;
	$getCompletedDetailSql = "SELECT * FROM project WHERE projectstatusId=3";
	$getCompletedDetail = mysqli_query($connF,$getCompletedDetailSql);
	$CompletedCount = mysqli_num_rows($getCompletedDetail);
	
	echo "$CompletedCount";
}
// Start Add Vacancy
function addVacancy(){
	global $connF;
	if(isset($_POST['addnewvacancy'])){
// 		echo '<pre>';print_r($_POST);exit;
		$postName = $_POST['postName'];
		$experience  = $_POST['experience'];
		$no_vacancies = $_POST['no_vacancies'];
		// $vacancyheaderTxt = $_POST['qualification'];
		$qualification = $_POST['qualification'];
		$skill1  = $_POST['skill1'];
		$location1 = $_POST['location1'];
// 		$vacancyheaderImage = $_FILES['vacancyheaderImage']['name'];
// 		$tempImg2 = $_FILES['vacancyheaderImage']['tmp_name'];
// 		move_uploaded_file($tempImg2,"resources/$vacancyheaderImage");
		$addVacancySql = "INSERT INTO vacancy(postName,experience,no_vacancies,qualification,skill1,location1) VALUES ('$postName','$experience','$no_vacancies','$qualification','$skill1','$location1')";
		$addVacancy = mysqli_query($connF,$addVacancySql);
		if($addVacancy){
			echo "<script>alert('Vacancy Added')</script>";
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
		
	}
}
// End Add Vacancy

// Start View Vacancy

function displayVacancy(){
	global $connF;
	$getVacancySql = "SELECT * FROM vacancy WHERE 1";
	$getVacancy = mysqli_query($connF,$getVacancySql);
	while($getVacancyRow = mysqli_fetch_array($getVacancy)){
		$vacancyId = $getVacancyRow['vacancyId'];
		$postName = $getVacancyRow['postName'];
		$no_vacancies = $getVacancyRow['no_vacancies'];
		$experience = $getVacancyRow['experience'];
		$qualification = $getVacancyRow['qualification'];
		$skill1 = $getVacancyRow['skill1'];
		$location1 = $getVacancyRow['location1'];
// 		$vacancyheaderTxt = $getVacancyRow['vacancyheaderTxt'];
// 		$vacancyheaderImage = $getVacancyRow['vacancyheaderImage'];
		echo "
			<tr>
				<td>$vacancyId</td>
				<td>$postName</td>
				<td>$no_vacancies</td>
				<td>$experience</td>
				<td>$qualification</td>
				'<td>$skill1</td>
				<td>$location1</td>
				
				<td><a href='index.php?editvacancy=$vacancyId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteVacancy=$vacancyId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>

			</tr>
		
		";

	}
}

// Start Edit Vacancy

function updateVacancy(){
	
	global $connF;
	
	if(isset($_POST['updatevacancy'])){
		
		$vacancyId = $_GET['editvacancy'];
		
		$getVacancySql = "SELECT * FROM vacancy WHERE vacancyId='$vacancyId'";
		$getVacancy = mysqli_query($connF,$getVacancySql);
		$getVacancyRow = mysqli_fetch_array($getVacancy);
		$postName = $_POST['postName'];
		$experience  = $_POST['experience'];
		$no_vacancies = $_POST['no_vacancies'];
// 		$vacancyheaderTxt = $_POST['vacancyheaderTxt'];
			$qualification = $_POST['qualification'];
		$skill1  = $_POST['skill1'];
		$location1 = $_POST['location1'];
// 		$vacancyheaderImageOld = $getVacancyRow['vacancyheaderImage'];
// 		$vacancyheaderImage = $_FILES['vacancyheaderImage']['name'];
		
		if(empty($vacancyheaderImage)){
			$vacancyheaderImage = $vacancyheaderImageOld;
		}
		$tempImg1 = $_FILES['vacancyheaderImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/$vacancyheaderImage");

        $updateVacancySql = "UPDATE vacancy SET postName='$postName',experience='$experience',no_vacancies='$no_vacancies',qualification='$qualification',skill1='$skill1',location1='$location1' WHERE vacancyId='$vacancyId'";
		$updateVacancy = mysqli_query($connF,$updateVacancySql);
		if($updateVacancy){
			echo "<script>alert('Vacancy Updated')</script>";
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
	    }
	}
// End Edit Vacancy

// Start Delete Vacancy
function deleteVacancy(){
	global $connF;
	if(isset($_GET['deleteVacancy'])){
		
		$VacancyId = $_GET['deleteVacancy'];
		$deleteVacancySql = "DELETE FROM vacancy WHERE vacancyId='$VacancyId'";
		$deleteVacancy = mysqli_query($connF,$deleteVacancySql);
		if($deleteVacancy){
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
	}
	
}
// End Delete Vacancy

// Count Vacancy

function countVacancy(){
	
	global $connF;
	$getVacancyDetailSql = "SELECT * FROM vacancy WHERE 1";
	$getVacancyDetail = mysqli_query($connF,$getVacancyDetailSql);
	$VacancyCount = mysqli_num_rows($getVacancyDetail);
	
	echo "$VacancyCount";
}
// Start Add Clients

function addClient(){
	global $connF;
	if(isset($_POST['addnewclient'])){
		
		$clientName = $_POST['clientName'];
		$clientImage = $_FILES['clientImage']['name'];
		$tempImg1 = $_FILES['clientImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/client_img/$clientImage");
		$addClientSql = "INSERT INTO clients(clientName,clientImage) VALUES ('$clientName','$clientImage')";
		$addClient = mysqli_query($connF,$addClientSql);
		if($addClient){
			echo "<script>alert('Client Added')</script>";
			echo "<script>window.open('index.php?addclient','_self')</script>";
		}
		
	}
}

// End Add Clients


// Start View Clients
function displayClient(){
	global $connF;
	$getClientSql = "SELECT * FROM clients WHERE 1";
	$getClient = mysqli_query($connF,$getClientSql);
	while($getClientRow = mysqli_fetch_array($getClient)){
		$clientId = $getClientRow['clientId'];
		$clientName = $getClientRow['clientName'];
		$clientImage = $getClientRow['clientImage'];
		echo "
			<tr>
				<td>$clientId</td>
				<td>$clientName</td>
				<td><img src='resources/client_img/$clientImage' style='width: 50px;height:50px;'></td>
                <td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteClient=$clientId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
                <td><a href='index.php?editclient=$clientId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";

	}
}
// End View Clients

// Start Edit Clients
function updateClient(){
	
	global $connF;
	
	if(isset($_POST['updateclient'])){
		
		$clientId = $_GET['editclient'];
		
		$getClientSql = "SELECT * FROM clients WHERE clientId='$clientId'";
		$getClient = mysqli_query($connF,$getClientSql);
		$getClientRow = mysqli_fetch_array($getClient);
		
		$clientImageOld = $getClientRow['clientImage'];
		$clientName = $_POST['clientName'];
		$clientImage = $_FILES['clientImage']['name'];
		
		if(empty($clientImage)){
			$clientImage = $clientImageOld;
		}
	
		$tempImg1 = $_FILES['clientImage']['tmp_name'];
		
		// Move the new image
		move_uploaded_file($tempImg1,"resources/client_img/$clientImage");

		// Remove the old image if the new image is uploaded
		if(!empty($clientImage) && $clientImage !== $clientImageOld){
			if(file_exists("resources/client_img/$clientImageOld")){
				unlink("resources/client_img/$clientImageOld");
			}
		}

        $updateClientSql = "UPDATE clients SET clientName='$clientName', clientImage='$clientImage' WHERE clientId='$clientId'";
		$updateClient = mysqli_query($connF,$updateClientSql);
		if($updateClient){
			echo "<script>alert('Client Updated')</script>";
			echo "<script>window.open('index.php?addclient','_self')</script>";
		}
		else{
			echo "<script>alert('Something went wrong!')</script>";
			echo "<script>window.open('index.php?addclient','_self')</script>";
		}
	}
}
// Start Delete Client
function deleteClient(){
	global $connF;
	if(isset($_GET['deleteClient'])){
		
		$ClientId = $_GET['deleteClient'];
		
		// Get the client image before deleting the record
		$getClientSql = "SELECT clientImage FROM clients WHERE clientId='$ClientId'";
		$getClient = mysqli_query($connF,$getClientSql);
		$getClientRow = mysqli_fetch_array($getClient);
		
		$clientImage = $getClientRow['clientImage'];
		
		// Delete the client record from the database
		$deleteClientSql = "DELETE FROM clients WHERE clientId='$ClientId'";
		$deleteClient = mysqli_query($connF,$deleteClientSql);
		
		if($deleteClient){
			// Remove the image from the folder
			if(!empty($clientImage) && file_exists("resources/client_img/$clientImage")){
				unlink("resources/client_img/$clientImage");
			}
			
			echo "<script>window.open('index.php?addclient','_self')</script>";
		}
	}
}

// End Delete Client

// Start Add Contact Us

function addContactUs(){
	global $connF;
	if(isset($_POST['addnewcontact'])){
		
		$contactAddress = $_POST['contactAddress'];

		$contactEmail_1 = $_POST['contactEmail_1'];
		$contactEmail_2 = $_POST['contactEmail_2'];
		$contactEmail_3 = $_POST['contactEmail_3'];

		$contactNum_1 = $_POST['contactNum_1'];
		$contactNum_2 = $_POST['contactNum_2'];
		$contactNum_3 = $_POST['contactNum_3'];


		// $clientImage = $_FILES['clientImage']['name'];
		// $tempImg1 = $_FILES['clientImage']['tmp_name'];
		// move_uploaded_file($tempImg1,"resources/client_img/$clientImage");
		$addContactSql = "INSERT INTO contactus(contactAddress,contactEmail_1,contactEmail_2,contactEmail_3,contactNum_1,contactNum_2,contactNum_3) VALUES ('$contactAddress','$contactEmail_1','$contactEmail_2','$contactEmail_3','$contactNum_1','$contactNum_2','$contactNum_3')";
		$addContact = mysqli_query($connF,$addContactSql);
		if($addContact){
			echo "<script>alert('Contact Added')</script>";
			echo "<script>window.open('index.php?addcontact','_self')</script>";
		}
		
	}
}

// End Add Contact Us

// Start View Contact Us

function displayContactUs()
{
	global $connF;
	$getContactSql = "SELECT * FROM contactus WHERE 1";
	$getContact = mysqli_query($connF,$getContactSql);
	while($getContactRow = mysqli_fetch_array($getContact)){
		$contactId  = $getContactRow['contactId'];
		$contactAddress = $getContactRow['contactAddress'];
		$contactEmail_1 = $getContactRow['contactEmail_1'];
		$contactEmail_2 = $getContactRow['contactEmail_2'];
		$contactEmail_3 = $getContactRow['contactEmail_3'];
		$contactNum_1 = $getContactRow['contactNum_1'];
		$contactNum_2 = $getContactRow['contactNum_2'];
		$contactNum_3 = $getContactRow['contactNum_3'];

		echo "
			<tr>
				<td>$contactId</td>
				<td>$contactAddress</td>
				<td>$contactEmail_1</td>
				<td>$contactEmail_2</td>
				<td>$contactEmail_3</td>
				<td>$contactNum_1</td>
				<td>$contactNum_2</td>
				<td>$contactNum_3</td>
		
                <td><a href='index.php?editcontact=$contactId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";

	}
}

// End View Contact Us

// Start Edit Contact Us
function updateContact(){
	global $connF;
	if(isset($_POST['updatecontact'])){
		
		$contactId = $_GET['editcontact'];
		
		$getContactSql = "SELECT * FROM contactus WHERE contactId='$contactId'";
		$getContact = mysqli_query($connF,$getContactSql);
		$getContactRow = mysqli_fetch_array($getContact);
		
		$contactAddress = $_POST['contactAddress'];

		$contactEmail_1 = $_POST['contactEmail_1'];
		$contactEmail_2 = $_POST['contactEmail_2'];
		$contactEmail_3 = $_POST['contactEmail_3'];

		$contactNum_1 = $_POST['contactNum_1'];
		$contactNum_2 = $_POST['contactNum_2'];
		$contactNum_3 = $_POST['contactNum_3'];
		
        $updateContactSql = "UPDATE contactus SET contactAddress='$contactAddress',contactEmail_1='$contactEmail_1',contactEmail_2='$contactEmail_2',contactEmail_3='$contactEmail_3',contactNum_1='$contactNum_1',contactNum_2 ='$contactNum_2',contactNum_3 ='$contactNum_3' WHERE contactId='$contactId'";
		$updateContact = mysqli_query($connF,$updateContactSql);
		if($updateContact){
			echo "<script>alert('Client Updated')</script>";
			echo "<script>window.open('index.php?addcontact','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addcontact','_self')</script>";
		}
	    }
	}
// End Edit Contact Us



