<?php

$servername = "localhost";
$username = "root";
$password = "";
$dbname = "anaya"; 
// $base_url="://localhost:8081/asmakgroup/"
$connF = mysqli_connect($servername,$username,$password,$dbname);

if($connF)
{
    echo "";
}
else
{
    echo "connection failed";
}




function generateRandomPassword(){
	
	$combination = 'qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM0123456789~!@#$%^&*()_+[]{}<>?';
	$combination = str_shuffle($combination);
	$randomPassword = substr($combination,0,8);
	return $randomPassword;
}

function sentConfirmMail($email,$name,$cCode){
	
	//PHPMailer Function
			$mail = new PHPMailer;
			$mail->isSMTP();
			$mail->SMTPDebug = 0;
			$mail->Debugoutput = 'html';
			$mail->Host = 'smtp.gmail.com';
			$mail->Port = 587;
			$mail->SMTPSecure = 'tls';
			$mail->SMTPAuth = true;
			$mail->Username = "mailer.nilkamal@gmail.com";
			$mail->Password = "nilkamal@123456";
			$mail->setFrom('mailer.nilkamal@gmail.com', 'nilkamal Support');
			$mail->addAddress($email, $name);
			$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
			$mail->Subject = 'Please Confirm Your nilkamal Account';
			$mail->Body = "
						<p>Hi! $name </p>
						<p>Thank you for registering on our site </p>
						<br><br><br>
						<b> Please visit My Account page on site to confirm your email </b>
						<br><br>
						Your nilkamal Account Confirmation Code:&nbsp; <strong>$cCode</strong>
						<br><br>
						<b><i>Important! Please verifiy your email just after logged into the site</i></b>
						";
			if (!$mail->send()) {
    			echo "<script>alert('Somthing Wrong! Please Contact Us')</script>";
			}
	
}


function recoverPassword(){
	
	global $connF;
	global $wrongpass;
	
	if(isset($_POST['recoverpass'])){
		
		$customerEmail = $_POST['cus_email'];
		
		//Google Recaptcha
		$sKey = "6LdScHYUAAAAAL6_FSP4Jgmv_Vd4-2sYytWiBt0K";
		$gResponse = $_POST['g-recaptcha-response'];
		$remoteIP = $_SERVER['REMOTE_ADDR'];
		$guRL = "s://www.google.com/recaptcha/api/siteverify?secret=$sKey&response=$gResponse&remoteip=$remoteIP";
		$retuenResponse = file_get_contents($guRL);
		$jsonResponse = json_decode($retuenResponse);
		
		$getCustomerSql = "SELECT * FROM customer WHERE cusEmail='$customerEmail'";
		$getCustomer = mysqli_query($connF,$getCustomerSql);
		$getCustomerRow = mysqli_fetch_array($getCustomer);
		$getCustomerCount = mysqli_num_rows($getCustomer);
		
		if($getCustomerCount > 0 || $jsonResponse->success){
			
			$randomPassword = generateRandomPassword();
			$encRandomPassword = md5($randomPassword);
			
			$setRandowPasswordSql = "UPDATE customer SET cusPassword='$encRandomPassword' WHERE cusEmail='$customerEmail'";
			$setRandowPassword = mysqli_query($connF,$setRandowPasswordSql);
			$customerName = $getCustomerRow['cusName'];


			//PHPMailer Function
			$mail = new PHPMailer;
			$mail->isSMTP();
			$mail->SMTPDebug = 0;
			$mail->Debugoutput = 'html';
			$mail->Host = 'smtp.gmail.com';
			$mail->Port = 587;
			$mail->SMTPSecure = 'tls';
			$mail->SMTPAuth = true;
			$mail->Username = "mailer.nilkamal@gmail.com";
			$mail->Password = "nilkamal@123456";
			$mail->setFrom('mailer.nilkamal@gmail.com', 'nilkamal Support');
			$mail->addAddress($customerEmail, $customerName);
			$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
			$mail->Subject = 'Your nilkamal Account Password';
			$mail->Body = "
						<b> This password is generated by nilkamal Servers </b>
						<br><br>
						Your nilkamal Account Password:&nbsp; <strong>$randomPassword</strong>
						<br><br>
						<b><i>Important! Please change your password just after logged into the site</i></b>
						";
			if (!$mail->send()) {
    			$wrongpass = "Somthing Wrong";
			} 
			else {
   				$wrongpass = "Password has been sent your email! Please check your inbox/spam folder";
			}
		}
		else{
			if(!$getCustomerCount>0){
				$wrongpass = "Email not found, Please check your email";
			}
			$wrongpass = "Please complete the Recaptcha!";
		}
	}
	
	
}

function setGetCookie(){
	
	global $random; 
	$random= rand(0, 9999999); 
	if(!isset($_COOKIE['user_cookie'])) {
    	setcookie('user_cookie',$random, time() + (86400), "/");//86400 = 1 day
	}
	else {
    	return $_COOKIE['user_cookie']; 
	}
	
}

function switchLoginLogout(){
	if(!isset($_SESSION['cusEmail'])){
		echo "<li><a href='register.php'>Register</a></li>";
		echo "<li><a href='login.php'>Login</a></li>";
	}else{
		echo "<li><a href='customers/myaccount.php?myorders'>My Account</a></li>";
		echo "<li><a href='logout.php'>Logout</a></li>";
	}
}

function switchLoginLogout1(){
	if(!isset($_SESSION['cusEmail'])){
		echo "<li class='nav-item dnone'><a href='register.php' class='nav-link'><span class='icon-user-plus' style='font-size: 24px; padding-right: 7px' data-toggle='tooltip' title='Login'></span><span class='dnone'>Register</span></a></li>";
echo "<li class='nav-item dnone'><a href='login.php' class='nav-link'><span class='icon-key' style='font-size: 24px; padding-right: 7px' data-toggle='tooltip' title='Login'></span><span class='dnone'>Login</a></li>";
		
	}else{
		echo "
<li class='nav-item dnone'><a href='customers/myaccount.php?myorders' class='nav-link'><span class='icon-folder' style='font-size: 24px; padding-right: 7px' data-toggle='tooltip' title='My Account'></span><span class='dnone'>My Account</span></a></li>"
		;
		echo "<li class='nav-item dnone'><a href='logout.php' class='nav-link'>Logout</a></li>";
	}
}


function changePassword(){
	
	global $connF;
	
	if(isset($_POST['changepassword'])){
		$currentUser = $_SESSION['cusEmail'];
		$getCustomerPasswordSql = "SELECT * FROM customer WHERE cusEmail='$currentUser'";
		$getCustomerPassword = mysqli_query($connF,$getCustomerPasswordSql);	
		$getCustomerPasswordRow = mysqli_fetch_array($getCustomerPassword);
		
		$currentPassword = $_POST['current_pass'];
		$newPassword = $_POST['new_pass'];
		$cNewPassword = $_POST['new_cpass'];
		
		$currentPasswordDB = $getCustomerPasswordRow['cusPassword'];
		$decryptCurrentPassword = md5($currentPasswordDB);
		
		if($currentPassword == $decryptCurrentPassword && $newPassword == $cNewPassword){
			$encryptNewPassword = md5($newPassword);
			$changePasswordSql = "UPDATE customer SET cusPassword='$encryptNewPassword' WHERE cusEmail = '$currentUser'";
			$changePassword = mysqli_query($connF,$changePasswordSql);
			echo "<script>alert('Password changed successfully!, Please login to contiune')</script>";
			session_destroy();
			echo "<script>window.open('../login.php','_self')</script>";
		}
		else if($currentPasswordDB != $currentPassword && $newPassword == $cNewPassword){
			
			echo "<script>alert('Your current password is wrong!')</script>";
		}
		else if($currentPasswordDB == $currentPassword && $newPassword != $cNewPassword){
			
			echo "<script>alert('Confirm password mismatch')</script>";
		}
		else{
			echo "<script>alert('Something wrong!')</script>";
		}
			
	}
}



function getAdminDetails(){
	
	global $connF;
	
	$currentAdmin = $_SESSION['email'];
	$adminDetailsSql = "SELECT * FROM admin WHERE adminEmail ='$currentAdmin'";
	$adminDetails = mysqli_query($connF,$adminDetailsSql);
	$adminDetailsRow = mysqli_fetch_array($adminDetails);
	
	$adminName = $adminDetailsRow['adminName'];
	echo "$adminName";	
}





function addServices(){
	global $connF;
	if(isset($_POST['addnewservices'])){
		
		$servicesName = $_POST['servicesName'];
		$servicesDescTxt = $_POST['servicesDescTxt'];
		$servicesImage = $_FILES['servicesImage']['name'];
		$servicesheaderImage = $_FILES['servicesheaderImage']['name'];
		$tempImg1 = $_FILES['servicesImage']['tmp_name'];
		$tempImg2 = $_FILES['servicesheaderImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/services_img/$servicesImage");
		move_uploaded_file($tempImg2,"resources/services_img/$servicesheaderImage");
		$addServicesSql = "INSERT INTO services(servicesName,servicesImage,servicesheaderImage,servicesDescTxt) VALUES ('$servicesName','$servicesImage','$servicesheaderImage','$servicesDescTxt')";
		$addServices = mysqli_query($connF,$addServicesSql);
		if($addServices){
			echo "<script>alert('Services Added')</script>";
			echo "<script>window.open('index.php?addservices','_self')</script>";
		}
		
	}
}





function displayServices(){
	global $connF;
	$getServicesSql = "SELECT * FROM services WHERE 1";
	$getServices = mysqli_query($connF,$getServicesSql);
	while($getServicesRow = mysqli_fetch_array($getServices)){
		$servicesId = $getServicesRow['servicesId'];
		$servicesName = $getServicesRow['servicesName'];
		$servicesImage = $getServicesRow['servicesImage'];
		$servicesheaderImage = $getServicesRow['servicesheaderImage'];
		$servicesDescTxt = $getServicesRow['servicesDescTxt'];
		echo "
			<tr>
				<td>$servicesId</td>
				<td>$servicesName</td>
				<td>$servicesDescTxt</td>
				<td><img src='resources/services_img/$servicesImage' style='width: 50px;height:50px;'></td>
				
				<td><a href='index.php?editservices=$servicesId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteServices=$servicesId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>

			</tr>
		
		";

	}
}
function updateServices(){
	
	global $connF;
	
	if(isset($_POST['updateservices'])){
		
		$servicesId = $_GET['editservices'];
		
		$getServicesSql = "SELECT * FROM services WHERE servicesId='$servicesId'";
		$getServices = mysqli_query($connF,$getServicesSql);
		$getServicesRow = mysqli_fetch_array($getServices);
		
		$servicesImageOld = $getServicesRow['servicesImage'];
		$servicesheaderImageOld = $getServicesRow['servicesheaderImage'];
		$servicesName = $_POST['servicesName'];
		$servicesDescTxt= $_POST['servicesDescTxt'];
		$servicesImage = $_FILES['servicesImage']['name'];
		$servicesheaderImage = $_FILES['servicesheaderImage']['name'];
		if(empty($servicesImage)){
			$servicesImage = $servicesImageOld;
		}
		if(empty($servicesheaderImage)){
			$servicesheaderImage = $servicesheaderImageOld;
		}
	
		$tempImg1 = $_FILES['servicesImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/services_img/$servicesImage");
		$tempImg2 = $_FILES['servicesheaderImage']['tmp_name'];
		move_uploaded_file($tempImg2,"resources/services_img/$servicesheaderImage");
		// if(!empty($servicesImageOld)){
		// 	unlink("resources/services_img/$servicesImage");
		// }

        $updateServicesSql = "UPDATE services SET servicesName='$servicesName',servicesImage='$servicesImage',servicesheaderImage='$servicesheaderImage',servicesDescTxt='$servicesDescTxt' WHERE servicesId='$servicesId'";
		$updateServices = mysqli_query($connF,$updateServicesSql);
		if($updateServices){
			echo "<script>alert('Services Updated')</script>";
			echo "<script>window.open('index.php?addservices','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addservices','_self')</script>";
		}
	    }
	}

function deleteServices(){
	global $connF;
	if(isset($_GET['deleteServices'])){
		
		$ServicesId = $_GET['deleteServices'];
		$deleteServicesSql = "DELETE FROM services WHERE servicesId='$ServicesId'";
		$deleteServices = mysqli_query($connF,$deleteServicesSql);
		if($deleteServices){
			echo "<script>window.open('index.php?addservices','_self')</script>";
		}
	}
	
}

function addSubService(){
	global $connF;
	if(isset($_POST['addnewsubservice'])){
		
		// $subservice = $_POST['subservice'];
		$ServicesId = $_POST['servicesId'];
		$subserviceDesc = $_POST['subservicedesc'];

		// $subserviceImage1 = $_FILES['subserviceImage1']['name'];
		// $tempImg1 = $_FILES['subserviceImage1']['tmp_name'];
		// move_uploaded_file($tempImg1,"resources/subservice_img/$subserviceImage1");

        // $subserviceImage2 = $_FILES['subserviceImage2']['name'];
		// $tempImg2 = $_FILES['subserviceImage2']['tmp_name'];
		// move_uploaded_file($tempImg2,"resources/subservice_img/$subserviceImage2");

        // $subserviceImage3 = $_FILES['subserviceImage3']['name'];
		// $tempImg3 = $_FILES['subserviceImage3']['tmp_name'];
		// move_uploaded_file($tempImg3,"resources/subservice_img/$subserviceImage3"); 

		$subserviceImage4 = $_FILES['subserviceImage4']['name'];
		$tempImg4 = $_FILES['subserviceImage4']['tmp_name'];
		move_uploaded_file($tempImg4,"resources/subservice_img/$subserviceImage4"); 


		$addSubServiceSql = "INSERT INTO subservice(servicesId,subservicedesc,subserviceImage4) VALUES ('$ServicesId','$subserviceDesc','$subserviceImage4')";
		$addSubService = mysqli_query($connF,$addSubServiceSql);
		if($addSubService){
			echo "<script>alert('Sub Service Added')</script>";
			echo "<script>window.open('index.php?addsubservice','_self')</script>";
		}
		
	}
}


function displaySubService(){
	global $connF;
	$getSubServiceSql = "SELECT * FROM subservice WHERE 1";
	$getSubService = mysqli_query($connF,$getSubServiceSql);
	while($getSubServiceRow = mysqli_fetch_array($getSubService)){
		$subserviceId = $getSubServiceRow['subserviceId'];
		$subservice = $getSubServiceRow['subservice'];
		$subservicedesc = $getSubServiceRow['subservicedesc'];
		$ServicesId = $getSubServiceRow['servicesId'];
		// $servicesImage = $getCategoryRow['servicesImage'];
		$getservicesNameSql = "SELECT * FROM services WHERE servicesId='$ServicesId'";
		$getservicesName = mysqli_query($connF,$getservicesNameSql);
		$getservicesNameRow = mysqli_fetch_array($getservicesName);
		$servicesName = $getservicesNameRow['servicesName'];
		echo "
			<tr>
				<td>$subserviceId</td>
				<td>$servicesName</td>
				<td>$subservice</td>
				<td>$subservicedesc</td>
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteSubService=$subserviceId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>			
				<td><a href='index.php?editsubservice=$subserviceId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";
	}
}
function updateSubService(){
	
	global $connF;
	
	if(isset($_POST['updatesubservice'])){
		
		$subserviceId = $_GET['editsubservice'];
		
		$getSubServiceSql = "SELECT * FROM subservice WHERE subserviceId='$subserviceId'";
		$getSubService = mysqli_query($connF,$getSubServiceSql);
		$getSubServiceRow = mysqli_fetch_array($getSubService);
		
		$subserviceImageOld1 = $getSubServiceRow['subserviceImage1'];
		$subserviceImageOld2 = $getSubServiceRow['subserviceImage2'];
		$subserviceImageOld3 = $getSubServiceRow['subserviceImage3'];
		$subserviceImageOld4 = $getSubServiceRow['subserviceImage4'];

		$subservice = $_POST['subservice'];
		$subserviceImage1 = $_FILES['subserviceImage1']['name'];
		$subserviceImage2 = $_FILES['subserviceImage2']['name'];
		$subserviceImage3 = $_FILES['subserviceImage3']['name'];
		$subserviceImage4 = $_FILES['subserviceImage4']['name'];

		$subservicedesc = $_POST['subservicedesc'];
		$ServicesId = $_POST['servicesId'];
	
		if(empty($subserviceImage1)){
			$subserviceImage1 = $subserviceImageOld1;
		}
		if(empty($subserviceImage2)){
			$subserviceImage2 = $subserviceImageOld2;
		}
		if(empty($subserviceImage3)){
			$subserviceImage3 = $subserviceImageOld3;
		}
		$tempImg1 = $_FILES['subserviceImage1']['tmp_name'];
		$tempImg2 = $_FILES['subserviceImage2']['tmp_name'];
		$tempImg3 = $_FILES['subserviceImage3']['tmp_name'];
		$tempImg4 = $_FILES['subserviceImage4']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/subservice_img/$subserviceImage1");
		move_uploaded_file($tempImg2,"resources/subservice_img/$subserviceImage2");
		move_uploaded_file($tempImg3,"resources/subservice_img/$subserviceImage3");
		move_uploaded_file($tempImg4,"resources/subservice_img/$subserviceImage4");


$updateSubServiceSql = "UPDATE subservice SET subservice='$subservice',servicesId='$ServicesId',subservicedesc='$subservicedesc',subserviceImage1='$subserviceImage1',subserviceImage2='$subserviceImage2',subserviceImage3='$subserviceImage3',subserviceImage4='$subserviceImage4' WHERE subserviceId='$subserviceId'";
		$updateSubService = mysqli_query($connF,$updateSubServiceSql);
		if($updateSubService){
			echo "<script>alert('Sub Service Updated')</script>";
			echo "<script>window.open('index.php?addsubservice','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addsubservice','_self')</script>";
		}
	}
	}

function deleteSubService(){
	global $connF;
	if(isset($_GET['deleteSubService'])){
		
		$subserviceId = $_GET['deleteSubService'];
		$deleteSubServiceSql = "DELETE FROM  subservice WHERE subserviceId='$subserviceId'";
		$deleteSubService = mysqli_query($connF,$deleteSubServiceSql);
		if($deleteSubService){
			echo "<script>window.open('index.php?addsubservice','_self')</script>";
		}
	}
	
}

function addProject(){
	global $connF;
	if(isset($_POST['addnewproject'])){
		
		$projectName = $_POST['projectName'];
		$projectCatId = $_POST['projectCatId'];
		$projectDesc = $_POST['projectDesc'];
		$projectImg = $_FILES['projectImg']['name'];
		$tempImg1 = $_FILES['projectImg']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/project_img/$projectImg");

		$addProjectSql = "INSERT INTO project(projectName,projectImg,projectDesc,projectCatId) VALUES ('$projectName','$projectImg','$projectDesc','$projectCatId')";
		$addProject = mysqli_query($connF,$addProjectSql);
		if($addProject){
			echo "<script>alert('Project Added')</script>";
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}
		
	}
}


function displayProject(){
	global $connF;
	$getProjectSql = "SELECT * FROM project WHERE 1";
	$getProject = mysqli_query($connF,$getProjectSql);
	while($getProjectRow = mysqli_fetch_array($getProject)){
		$projectId = $getProjectRow['projectId'];
		$projectName = $getProjectRow['projectName'];
		$projectImg = $getProjectRow['projectImg'];
		$projectDesc = $getProjectRow['projectDesc'];
		$projectCatId = $getProjectRow['projectCatId'];
		$getprojectCatNameSql = "SELECT * FROM projectcategory WHERE projectCatId='$projectCatId'";
		$getprojectCatName = mysqli_query($connF,$getprojectCatNameSql);
		$getprojectCatNameRow = mysqli_fetch_array($getprojectCatName);
		$projectCatName = $getprojectCatNameRow['projectCatName'];
		echo "
			<tr>
				<td>$projectId</td>
				<td>$projectName</td>
				<td>$projectDesc</td>
			<td><img src='resources/project_img/$projectImg' style='width: 50px;height:50px;'></td>

				<td>$projectCatName</td>
				<td><a href='index.php?editproject=$projectId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>
		<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteProject=$projectId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>

			</tr>
		
		";

	}
}
function updateProject(){
	
	global $connF;
	
	if(isset($_POST['editproject'])){
		
		$projectId = $_GET['editproject'];
		
		$getProjectSql = "SELECT * FROM project WHERE projectId='$projectId'";
		$getProject = mysqli_query($connF,$getProjectSql);
		$getProjectRow = mysqli_fetch_array($getProject);
		
		$projectName = $_POST['projectName'];
		$projectImg = $_FILES['projectImg']['name'];

		$projectDesc = $_POST['projectDesc'];
		$projectCatId=$_POST['projectCatId'];
		$projectImgOld = $getProjectRow['projectImg'];

		
		if(empty($projectImg)){
			$projectImg = $projectImgOld;
		}
		$tempImg1 = $_FILES['projectImg']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/project_img/$projectImg");

        $updateProjectSql = "UPDATE project SET projectName='$projectName',projectImg='$projectImg',projectDesc='$projectDesc',projectCatId='$projectCatId' WHERE projectId='$projectId'";
		$updateProject = mysqli_query($connF,$updateProjectSql);
		if($updateProject){
			echo "<script>alert('Project Updated')</script>";
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}
	    }
	}

function deleteProject(){
	global $connF;
	if(isset($_GET['deleteProject'])){
		
		$ProjectId = $_GET['deleteProject'];
		$deleteProjectSql = "DELETE FROM project WHERE projectId='$ProjectId'";
		$deleteProject = mysqli_query($connF,$deleteProjectSql);
		if($deleteProject){
			echo "<script>window.open('index.php?addproject','_self')</script>";
		}
	}
	
}

function addProjectCategory(){
    global $connF;
    if(isset($_POST['addnewprojectcategory'])){
        
        $projectCatName = $_POST['projectCatName'];

        // Check if the file has been uploaded
        if (isset($_FILES['projectCatImg']) && $_FILES['projectCatImg']['error'] === UPLOAD_ERR_OK) {
            $projectCatImg = $_FILES['projectCatImg']['name'];
            $tempImg1 = $_FILES['projectCatImg']['tmp_name'];
            
            // Move the uploaded file
            if (move_uploaded_file($tempImg1, "resources/projectcategory_img/$projectCatImg")) {
                
                // Insert the data into the database
                $addProjectCatSql = "INSERT INTO projectcategory(projectCatName, projectCatImg) VALUES ('$projectCatName','$projectCatImg')";
                $addProjectCat = mysqli_query($connF, $addProjectCatSql);
                
                if($addProjectCat){
                    echo "<script>alert('Project Category Added')</script>";
                    echo "<script>window.open('index.php?addprojectcategory','_self')</script>";
                } else {
                    echo "<script>alert('Database error: Project Category not added')</script>";
                }
            } else {
                echo "<script>alert('Failed to upload the image.')</script>";
            }
        } else {
            echo "<script>alert('No file uploaded or file upload error.')</script>";
        }
    }
}


function ViewProjectCat(){
	global $connF;
	$getProjectCatSql = "SELECT * FROM projectcategory WHERE 1";
	$getProjectCat = mysqli_query($connF,$getProjectCatSql);
	while($getProjectCatRow = mysqli_fetch_array($getProjectCat)){

		$projectCatId = $getProjectCatRow['projectCatId'];
		$projectCatImg = $getProjectCatRow['projectCatImg'];
        $projectCatName = $getProjectCatRow['projectCatName'];
		
		echo "
			<tr>
				<td>$projectCatId</td>
				<td>$projectCatName</td>
                
				<td><img src='resources/projectcategory_img/$projectCatImg' style='width: 50px;height:50px;'></td>
				"; echo"
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteProjectCat=$projectCatId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>			
				<td><a href='index.php?editprojectcategory=$projectCatId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";
	}
}
function editprojectcat() {
	global $connF;

	if(isset($_POST['editprojectcat'])){
		$projectCatId = $_GET['editprojectcategory'];
			
		$getprojectCatSql = "SELECT * FROM projectcategory WHERE projectCatId='$projectCatId'";
		$getprojectCat = mysqli_query($connF,$getprojectCatSql);
		$getprojectCatRow = mysqli_fetch_array($getprojectCat);

		$projectCatName = $_POST['projectCatName'];
		$projectCatImg=$_POST['projectCatImg'];
		$projectCatImgOld = $getprojectCatRow['projectCatImg'];
		
		$projectCatImg = $_FILES['projectCatImg']['name'];
		
		if(empty($projectCatImg)){
			$projectCatImg = $projectCatImgOld;
		}
		$tempImg1 = $_FILES['projectCatImg']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/projectcategory_img/$projectCatImg");
		
		$updateProjectCatSql = "UPDATE projectcategory SET projectCatName='$projectCatName', projectCatImg='$projectCatImg' WHERE projectCatId='$projectCatId'";
		$updateProjectCat = mysqli_query($connF, $updateProjectCatSql);

		if($updateProjectCat){
			echo "<script>alert('Project Updated');</script>";
			echo "<script>window.open('index.php?addprojectcategory','_self');</script>";
		} else {
			echo "<script>alert('Something went wrong!');</script>";
			echo "<script>window.open('index.php?addprojectcategory','_self');</script>";
		}
	}
}


function deleteProjectCat(){
	global $connF;
	if(isset($_GET['deleteProjectCat'])){
		
		$projectCatId = $_GET['deleteProjectCat'];
		$deleteProjectCatSql = "DELETE FROM  projectcategory WHERE projectCatId='$projectCatId'";
		$deleteProjectCat = mysqli_query($connF,$deleteProjectCatSql);
		if($deleteProjectCat){
			echo "<script>window.open('index.php?addprojectcategory','_self')</script>";
		}
	}
	
}



// ABOUT US


function addAboutUs(){
	global $connF;
	if(isset($_POST['addaboutus'])){
		//  $aboutheaderTxt = $_POST['aboutheaderTxt'];
		$companyOverview = $_POST['companyOverview'];
		$projectCatImg = $_FILES['projectCatImg']['name'];
		$tempImg1 = $_FILES['projectCatImg']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/aboutus_img/$projectCatImg");
        //VISION
       
        $companyVision = $_POST['companyVision'];
		$companyvisionImage = $_FILES['companyvisionImage']['name'];
		$tempImg2 = $_FILES['companyvisionImage']['tmp_name'];
		move_uploaded_file($tempImg2,"resources/aboutus_img/$companyvisionImage");
        //PHILOSOPHY
        $companyPhilosophy = $_POST['companyPhilosophy'];
		$companyphilosophyImage = $_FILES['companyphilosophyImage']['name'];
		$tempImg3 = $_FILES['companyphilosophyImage']['tmp_name'];
		move_uploaded_file($tempImg3,"resources/aboutus_img/$companyphilosophyImage");
		
		$aboutheaderImage = $_FILES['aboutheaderImage']['name'];
		$tempImg4 = $_FILES['aboutheaderImage']['tmp_name'];
		move_uploaded_file($tempImg4,"resources/aboutus_img/$aboutheaderImage");

		$addAboutUsSql = "INSERT INTO aboutus(companyOverview,projectCatImg,companyVision,companyvisionImage,companyPhilosophy,companyphilosophyImage,aboutheaderImage) VALUES ('$companyOverview','$projectCatImg','$companyVision','$companyvisionImage','$companyPhilosophy','$companyphilosophyImage','$aboutheaderImage')";
		$addAboutUs = mysqli_query($connF,$addAboutUsSql);
		if($addAboutUs){
			echo "<script>alert('About Us Added')</script>";
			echo "<script>window.open('index.php?addaboutus','_self')</script>";
		}
		
	}
}





function displayAboutUs(){
	global $connF;
	$getAboutUsSql = "SELECT * FROM aboutus WHERE 1";
	$getAboutUs = mysqli_query($connF,$getAboutUsSql);
	while($getAboutUsRow = mysqli_fetch_array($getAboutUs)){
		$aboutusId = $getAboutUsRow['aboutusId'];
		// $aboutheaderTxt = $getAboutUsRow['aboutheaderTxt'];
		$companyOverview = $getAboutUsRow['companyOverview'];
		$projectCatImg = $getAboutUsRow['projectCatImg'];
        $companyVision = $getAboutUsRow['companyVision'];
		$companyvisionImage = $getAboutUsRow['companyvisionImage'];
        $companyPhilosophy = $getAboutUsRow['companyPhilosophy'];
		$companyphilosophyImage = $getAboutUsRow['companyphilosophyImage'];
		$aboutheaderImage   = $getAboutUsRow['aboutheaderImage'];
		echo "
		<thead><th>
<a href='index.php?editaboutus=$aboutusId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a>
		</th></thead>
			<tr>
				<td>OVERVIEW</td>
				<td>$companyOverview</td>
				<td><img src='resources/aboutus_img/$projectCatImg' style='width: 50px;height:50px;'></td>
				</tr>
				
			
				</tr>
				<tr>
				<td>VISSION</td>
				<td>$companyVision</td>
				<td><img src='resources/aboutus_img/$companyvisionImage' style='width: 50px;height:50px;'></td>
				
				</tr>
				<tr>
					<td>PHILOSOPHY</td>
			<td>$companyPhilosophy</td>
				<td><img src='resources/aboutus_img/$companyphilosophyImage' style='width: 50px;height:50px;'></td>
		
			</tr>
          
           
		";
		// <td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteAboutUs=$aboutusId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>

	}
}
function updateAboutUs(){
	
	global $connF;
	
	if(isset($_POST['updateaboutus'])){
		
		$aboutusId = $_GET['editaboutus'];
		
		$getAboutUsSql = "SELECT * FROM aboutus WHERE aboutusId='$aboutusId'";
		$getAboutUs = mysqli_query($connF,$getAboutUsSql);
		$getAboutUsRow = mysqli_fetch_array($getAboutUs);
		// $aboutheaderTxt = $_POST['aboutheaderTxt'];
		$projectCatImgOld = $getAboutUsRow['projectCatImg'];
		$companyOverview = $_POST['companyOverview'];
		$projectCatImg = $_FILES['projectCatImg']['name'];
		
		if(empty($projectCatImg)){
			$projectCatImg = $projectCatImgOld;
		}
		$tempImg1 = $_FILES['projectCatImg']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/aboutus_img/$projectCatImg");
		
        //VISION
        $companyvisionImageOld = $getAboutUsRow['companyvisionImage'];
		$companyVision = $_POST['companyVision'];
		$companyvisionImage = $_FILES['companyvisionImage']['name'];
		
		if(empty($companyvisionImage)){
			$companyvisionImage = $companyvisionImageOld;
		}
		$tempImg2 = $_FILES['companyvisionImage']['tmp_name'];
		move_uploaded_file($tempImg2,"resources/aboutus_img/$companyvisionImage");

        // PHILOSOPHY
        $companyphilosophyImageOld = $getAboutUsRow['companyphilosophyImage'];
		$companyPhilosophy = $_POST['companyPhilosophy'];
		$companyphilosophyImage = $_FILES['companyphilosophyImage']['name'];
		
		if(empty($companyphilosophyImage)){
			$companyphilosophyImage = $companyphilosophyImageOld;
		}
		$tempImg3 = $_FILES['companyphilosophyImage']['tmp_name'];
		move_uploaded_file($tempImg3,"resources/aboutus_img/$companyphilosophyImage");

    $aboutheaderImageOld = $getAboutUsRow['aboutheaderImage'];
	$aboutheaderImage = $_FILES['aboutheaderImage']['name'];
		
		if(empty($aboutheaderImage)){
			$aboutheaderImage = $aboutheaderImageOld;
		}
		$tempImg4 = $_FILES['companyphilosophyImage']['tmp_name'];
		move_uploaded_file($tempImg4,"resources/aboutus_img/$aboutheaderImage");
        $updateAboutUsSql = "UPDATE aboutus SET companyOverview='$companyOverview',projectCatImg='$projectCatImg',companyVision='$companyVision',companyvisionImage='$companyvisionImage',companyPhilosophy='$companyPhilosophy',companyphilosophyImage='$companyphilosophyImage',aboutheaderImage='$aboutheaderImage' WHERE aboutusId='$aboutusId'";
		$updateAboutUs = mysqli_query($connF,$updateAboutUsSql);
		if($updateAboutUs){
			echo "<script>alert('About Us Updated')</script>";
			echo "<script>window.open('index.php?addaboutus','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addaboutus','_self')</script>";
		}
	    }
	}

function deleteAboutUs(){
	global $connF;
	if(isset($_GET['deleteAboutUs'])){
		
		$AboutUsId = $_GET['deleteAboutUs'];
		$deleteAboutUsSql = "DELETE FROM aboutus WHERE aboutusId='$AboutUsId'";
		$deleteAboutUs = mysqli_query($connF,$deleteAboutUsSql);
		if($deleteAboutUs){
			echo "<script>window.open('index.php?addaboutus','_self')</script>";
		}
	}
	
}

// DEPARTMENT
 function addDepartment(){
	global $connF;
	if(isset($_POST['addnewdepartment'])){
		
		$departmentName = $_POST['departmentName'];
		$addDepartmentSql = "INSERT INTO department(departmentName) VALUES ('$departmentName')";
		$addDepartment = mysqli_query($connF,$addDepartmentSql);
		if($addDepartment){
			echo "<script>alert('Department Added')</script>";
			echo "<script>window.open('index.php?add_department','_self')</script>";
		}
		
	}
}





function displayDepartment(){
	global $connF;
	$getDepartmentSql = "SELECT * FROM department WHERE 1";
	$getDepartment = mysqli_query($connF,$getDepartmentSql);
	while($getDepartmentRow = mysqli_fetch_array($getDepartment)){
		$departmentId = $getDepartmentRow['departmentId'];
		$departmentName = $getDepartmentRow['departmentName'];
		echo "
			<tr>
				<td>$departmentId</td>
				<td>$departmentName</td>
                <td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteDepartment=$departmentId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
                <td><a href='index.php?editdepartment=$departmentId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";

	}
}
function updateDepartment(){
	
	global $connF;
	
	if(isset($_POST['updatedepartment'])){
		
		$departmentId = $_GET['editdepartment'];
		
		$getDepartmentSql = "SELECT * FROM department WHERE departmentId='$departmentId'";
		$getDepartment = mysqli_query($connF,$getDepartmentSql);
		$getDepartmentRow = mysqli_fetch_array($getDepartment);
		
		$departmentName = $_POST['departmentName'];
		$updateDepartmentSql = "UPDATE department SET departmentName='$departmentName' WHERE departmentId='$departmentId'";
		$updateDepartment = mysqli_query($connF,$updateDepartmentSql);
		if($updateDepartment){
			echo "<script>alert('Department Updated')</script>";
			echo "<script>window.open('index.php?add_department','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?add_department','_self')</script>";
		}
	    }
	}

function deleteDepartment(){
	global $connF;
	if(isset($_GET['deleteDepartment'])){
		
		$DepartmentId = $_GET['deleteDepartment'];
		$deleteDepartmentSql = "DELETE FROM department WHERE departmentId='$DepartmentId'";
		$deleteDepartment = mysqli_query($connF,$deleteDepartmentSql);
		if($deleteDepartment){
			echo "<script>window.open('index.php?add_department','_self')</script>";
		}
	}
	
}

//DESIGNATION

function addDesignation(){
	global $connF;
	if(isset($_POST['addnewdesignation'])){
		
		$designation = $_POST['designation'];
		$DepartmentId = $_POST['departmentId'];

		$addDesignationSql = "INSERT INTO designation(designation,departmentId) VALUES ('$designation','$DepartmentId')";
		$addDesignation = mysqli_query($connF,$addDesignationSql);
		if($addDesignation){
			echo "<script>alert('Designation Added')</script>";
			echo "<script>window.open('index.php?add_designation','_self')</script>";
		}
		
	}
}


function displayDesignation(){
	global $connF;
	$getDesignationSql = "SELECT * FROM designation WHERE 1";
	$getDesignation = mysqli_query($connF,$getDesignationSql);
	while($getDesignationRow = mysqli_fetch_array($getDesignation)){
		$designationId = $getDesignationRow['designationId'];
		$designation = $getDesignationRow['designation'];
		$DepartmentId = $getDesignationRow['departmentId'];
		$getdepartmentNameSql = "SELECT * FROM department WHERE departmentId='$DepartmentId'";
		$getdepartmentName = mysqli_query($connF,$getdepartmentNameSql);
		$getdepartmentNameRow = mysqli_fetch_array($getdepartmentName);
		$departmentName = $getdepartmentNameRow['departmentName'];
		echo "
			<tr>
				<td>$designationId</td>
				<td>$departmentName</td>
				<td>$designation</td>
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteDesignation=$designationId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>			
				<td><a href='index.php?editdesignation=$designationId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";
	}
}
function updateDesignation(){
	
	global $connF;
	
	if(isset($_POST['updatedesignation'])){
		
		$designationId = $_GET['editdesignation'];
		
		$getDesignationSql = "SELECT * FROM designation WHERE designationId='$designationId'";
		$getDesignation = mysqli_query($connF,$getDesignationSql);
		$getDesignationRow = mysqli_fetch_array($getDesignation);
		
		$designation = $_POST['designation'];
		$DepartmentId = $_POST['departmentId'];
	
    $updateDesignationSql = "UPDATE designation SET designation='$designation',departmentId='$DepartmentId' WHERE designationId='$designationId'";
		$updateDesignation = mysqli_query($connF,$updateDesignationSql);
		if($updateDesignation){
			echo "<script>alert('Designation Updated')</script>";
			echo "<script>window.open('index.php?add_designation','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?add_designation','_self')</script>";
		}
	}
	}

function deleteDesignation(){
	global $connF;
	if(isset($_GET['deleteDesignation'])){
		
		$designationId = $_GET['deleteDesignation'];
		$deleteDesignationSql = "DELETE FROM  designation WHERE designationId='$designationId'";
		$deleteDesignation = mysqli_query($connF,$deleteDesignationSql);
		if($deleteDesignation){
			echo "<script>window.open('index.php?add_designation','_self')</script>";
		}
	}
	
}

// MEMBER
function addMember(){
	global $connF;
	if(isset($_POST['addnewmember'])){
		$memberName = $_POST['memberName'];
        $departmentId = $_POST['departmentId'];
		$designationId = $_POST['designationId'];
        $memberDesc = $_POST['memberDesc'];
		$memberImage = $_FILES['memberImage']['name'];
		$tempImg2 = $_FILES['memberImage']['tmp_name'];
		move_uploaded_file($tempImg2,"resources/member_img/$memberImage");
		$addMemberSql = "INSERT INTO member(memberName,departmentId,designationId,memberDesc,memberImage) VALUES ('$memberName','$departmentId','$designationId','$memberDesc','$memberImage')";
		$addMember = mysqli_query($connF,$addMemberSql);
		if($addMember){
			echo "<script>alert('Member Added')</script>";
			echo "<script>window.open('index.php?addmember','_self')</script>";
		}
		
	}
}

function displayMember(){
	global $connF;
	$getMemberSql = "SELECT * FROM member WHERE 1";
	$getMember = mysqli_query($connF,$getMemberSql);
	while($getMemberRow = mysqli_fetch_array($getMember)){
		$memberId = $getMemberRow['memberId'];
		$memberName = $getMemberRow['memberName'];
		$memberDesc = $getMemberRow['memberDesc'];
		$departmentId = $getMemberRow['departmentId'];
		$designationId = $getMemberRow['designationId'];
		$memberImage = $getMemberRow['memberImage'];
        // if(!empty($memberImage) && file_exists($memberImage))
		// 		{
		// 			unlink($memberImage);
		// 		}
		$getdepartmentNameSql = "SELECT * FROM department WHERE departmentId='$departmentId'";
		$getdepartmentName = mysqli_query($connF,$getdepartmentNameSql);
		$getdepartmentNameRow = mysqli_fetch_array($getdepartmentName);
		$departmentName = $getdepartmentNameRow['departmentName'];

		$getdesignationSql = "SELECT * FROM designation WHERE designationId='$designationId'";
		$getdesignation = mysqli_query($connF,$getdesignationSql);
		$getdesignationRow = mysqli_fetch_array($getdesignation);
		$designation = $getdesignationRow['designation'];

		
		echo "
			<tr>
				<td>$memberId</td>
				<td>$memberName</td>
				<td>$departmentName</td>
				<td>$designation</td>
				<td>$memberDesc</td>
				<td><img src='resources/member_img/$memberImage' style='width: 50px;height:50px;'></td>
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteMember=$memberId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>			
				<td><a href='index.php?editmember=$memberId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";
	}
}
function deleteMember(){
	global $connF;
	if(isset($_GET['deleteMember'])){
		
		$memberId = $_GET['deleteMember'];
		$deleteMemberSql = "DELETE FROM member WHERE memberId='$memberId'";
		$deleteMember = mysqli_query($connF,$deleteMemberSql);
		if($deleteMember){
			echo "<script>window.open('index.php?addmember','_self')</script>";
		}
	}
}

 function updateMember(){
	
	global $connF;
	
	if(isset($_POST['updatemember'])){
		
		$memberId = $_GET['editmember'];
		
		$getMemberSql = "SELECT * FROM member WHERE memberId='$memberId'";
		$getMember = mysqli_query($connF,$getMemberSql);
		$getMemberRow = mysqli_fetch_array($getMember);
		
		$memberImageOld = $getMemberRow['memberImage'];
		$memberName = $_POST['memberName'];
		$memberImage = $_FILES['memberImage']['name'];
		$memberDesc = $_POST['memberDesc'];
		$DepartmentId = $_POST['departmentId'];
		$DesignationId = $_POST['designationId'];
		
		if(empty($memberImage)){
			$memberImage = $memberImageOld;
		}
		$tempImg1 = $_FILES['memberImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/member_img/$memberImage");
		
		//

    $updateMemberSql = "UPDATE member SET memberName='$memberName',departmentId='$DepartmentId',designationId='$DesignationId',memberDesc='$memberDesc',memberImage='$memberImage' WHERE memberId='$memberId'";
		$updateMember = mysqli_query($connF,$updateMemberSql);
		if($updateMember){
			echo "<script>alert('Member Updated')</script>";
			echo "<script>window.open('index.php?addmember','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addmember','_self')</script>";
		}
	}
	}

//VACANCY
function addVacancy(){
	global $connF;
	if(isset($_POST['addnewvacancy'])){
// 		echo '<pre>';print_r($_POST);exit;
		$postName = $_POST['postName'];
		$experience  = $_POST['experience'];
		$no_vacancies = $_POST['no_vacancies'];
		// $vacancyheaderTxt = $_POST['qualification'];
		$qualification = $_POST['qualification'];
		$skill1  = $_POST['skill1'];
		$location1 = $_POST['location1'];
// 		$vacancyheaderImage = $_FILES['vacancyheaderImage']['name'];
// 		$tempImg2 = $_FILES['vacancyheaderImage']['tmp_name'];
// 		move_uploaded_file($tempImg2,"resources/$vacancyheaderImage");
		$addVacancySql = "INSERT INTO vacancy(postName,experience,no_vacancies,qualification,skill1,location1) VALUES ('$postName','$experience','$no_vacancies','$qualification','$skill1','$location1')";
		$addVacancy = mysqli_query($connF,$addVacancySql);
		if($addVacancy){
			echo "<script>alert('Vacancy Added')</script>";
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
		
	}
}


function displayVacancy(){
	global $connF;
	$getVacancySql = "SELECT * FROM vacancy WHERE 1";
	$getVacancy = mysqli_query($connF,$getVacancySql);
	while($getVacancyRow = mysqli_fetch_array($getVacancy)){
		$vacancyId = $getVacancyRow['vacancyId'];
		$postName = $getVacancyRow['postName'];
		$no_vacancies = $getVacancyRow['no_vacancies'];
		$experience = $getVacancyRow['experience'];
		$qualification = $getVacancyRow['qualification'];
		$skill1 = $getVacancyRow['skill1'];
		$location1 = $getVacancyRow['location1'];
// 		$vacancyheaderTxt = $getVacancyRow['vacancyheaderTxt'];
// 		$vacancyheaderImage = $getVacancyRow['vacancyheaderImage'];
		echo "
			<tr>
				<td>$vacancyId</td>
				<td>$postName</td>
				<td>$no_vacancies</td>
				<td>$experience</td>
				<td>$qualification</td>
				'<td>$skill1</td>
				<td>$location1</td>
				
				<td><a href='index.php?editvacancy=$vacancyId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteVacancy=$vacancyId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>

			</tr>
		
		";

	}
}
function updateVacancy(){
	
	global $connF;
	
	if(isset($_POST['updatevacancy'])){
		
		$vacancyId = $_GET['editvacancy'];
		
		$getVacancySql = "SELECT * FROM vacancy WHERE vacancyId='$vacancyId'";
		$getVacancy = mysqli_query($connF,$getVacancySql);
		$getVacancyRow = mysqli_fetch_array($getVacancy);
		$postName = $_POST['postName'];
		$experience  = $_POST['experience'];
		$no_vacancies = $_POST['no_vacancies'];
// 		$vacancyheaderTxt = $_POST['vacancyheaderTxt'];
			$qualification = $_POST['qualification'];
		$skill1  = $_POST['skill1'];
		$location1 = $_POST['location1'];
// 		$vacancyheaderImageOld = $getVacancyRow['vacancyheaderImage'];
// 		$vacancyheaderImage = $_FILES['vacancyheaderImage']['name'];
		
		if(empty($vacancyheaderImage)){
			$vacancyheaderImage = $vacancyheaderImageOld;
		}
		$tempImg1 = $_FILES['vacancyheaderImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/$vacancyheaderImage");

        $updateVacancySql = "UPDATE vacancy SET postName='$postName',experience='$experience',no_vacancies='$no_vacancies',qualification='$qualification',skill1='$skill1',location1='$location1' WHERE vacancyId='$vacancyId'";
		$updateVacancy = mysqli_query($connF,$updateVacancySql);
		if($updateVacancy){
			echo "<script>alert('Vacancy Updated')</script>";
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
	    }
	}

function deleteVacancy(){
	global $connF;
	if(isset($_GET['deleteVacancy'])){
		
		$VacancyId = $_GET['deleteVacancy'];
		$deleteVacancySql = "DELETE FROM vacancy WHERE vacancyId='$VacancyId'";
		$deleteVacancy = mysqli_query($connF,$deleteVacancySql);
		if($deleteVacancy){
			echo "<script>window.open('index.php?addvacancy','_self')</script>";
		}
	}
	
}

// EVENTS

function addEvent(){
	global $connF;
	if(isset($_POST['addnewevent'])){
		
		$eventName = $_POST['eventName'];
		$eventImage = $_FILES['eventImage']['name'];
		$tempImg1 = $_FILES['eventImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/event_img/$eventImage");
		$addEventSql = "INSERT INTO events(eventName,eventImage) VALUES ('$eventName','$eventImage')";
		$addEvent = mysqli_query($connF,$addEventSql);
		if($addEvent){
			echo "<script>alert('Event Added')</script>";
			echo "<script>window.open('index.php?addevent','_self')</script>";
		}
		
	}
}





function displayEvent(){
	global $connF;
	$getEventSql = "SELECT * FROM events WHERE 1";
	$getEvent = mysqli_query($connF,$getEventSql);
	while($getEventRow = mysqli_fetch_array($getEvent)){
		$eventId = $getEventRow['eventId'];
		$eventName = $getEventRow['eventName'];
		$eventImage = $getEventRow['eventImage'];
		echo "
			<tr>
				<td>$eventId</td>
				<td>$eventName</td>
				<td><img src='resources/event_img/$eventImage' style='width: 50px;height:50px;'></td>
                <td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteEvent=$eventId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
                <td><a href='index.php?editevent=$eventId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";

	}
}
function updateEvent(){
	
	global $connF;
	
	if(isset($_POST['updateevent'])){
		
		$eventId = $_GET['editevent'];
		
		$getEventSql = "SELECT * FROM events WHERE eventId='$eventId'";
		$getEvent = mysqli_query($connF,$getEventSql);
		$getEventRow = mysqli_fetch_array($getEvent);
		
		$eventImageOld = $getEventRow['eventImage'];
		$eventName = $_POST['eventName'];
		$eventImage = $_FILES['eventImage']['name'];
		
		if(empty($eventImage)){
			$eventImage = $eventImageOld;
		}
	
		$tempImg1 = $_FILES['eventImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/event_img/$eventImage");
		// if(!empty($eventImageOld)){
		// 	unlink("resources/event_img/$eventImage");
		// }

        $updateEventSql = "UPDATE events SET eventName='$eventName',eventImage='$eventImage' WHERE eventId='$eventId'";
		$updateEvent = mysqli_query($connF,$updateEventSql);
		if($updateEvent){
			echo "<script>alert('Event Updated')</script>";
			echo "<script>window.open('index.php?addevent','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addevent','_self')</script>";
		}
	    }
	}

function deleteEvent(){
	global $connF;
	if(isset($_GET['deleteEvent'])){
		
		$EventId = $_GET['deleteEvent'];
		$deleteEventSql = "DELETE FROM events WHERE eventId='$EventId'";
		$deleteEvent = mysqli_query($connF,$deleteEventSql);
		if($deleteEvent){
			echo "<script>window.open('index.php?addevent','_self')</script>";
		}
	}
	
}

//EVENT DATA

function addEventData(){
	global $connF;
	if(isset($_POST['addneweventdata'])){
	
		$EventId = $_POST['eventId'];
		$uploadFolder = 'resources/event_img/';
		foreach ($_FILES['imageFile']['tmp_name'] as $key => $image) {
			$imageTmpName = $_FILES['imageFile']['tmp_name'][$key];
			$imageName = $_FILES['imageFile']['name'][$key];
		$result =  move_uploaded_file($imageTmpName,$uploadFolder.$imageName);
		// $images_name ="";
			
			// save to database
			$query = "INSERT INTO eventdata SET eventdataImage1='$imageName',eventId = '$EventId'; " ;
			$run = $connF->query($query) or die("Error in saving image".$connF->error);
		}
		if ($result) {
			echo '<script>alert("Images uploaded successfully !")</script>';
			echo '<script>window.location.href="index.php?addeventdata";</script>';
		}
		
	}
}


function displayEventData(){
	global $connF;
	$getEventDataSql = "SELECT * FROM eventdata WHERE 1";
	$getEventData = mysqli_query($connF,$getEventDataSql);
	while($getEventDataRow = mysqli_fetch_array($getEventData)){
		$eventdataId = $getEventDataRow['eventdataId'];
		$eventdataImage1 = $getEventDataRow['eventdataImage1'];
        // $eventdataImage2 = $getEventDataRow['eventdataImage2'];
        // $eventdataImage3 = $getEventDataRow['eventdataImage3'];
		$EventId = $getEventDataRow['eventId'];
		// $eventImage = $getCategoryRow['eventImage'];
		$geteventNameSql = "SELECT * FROM events WHERE eventId='$EventId'";
		$geteventName = mysqli_query($connF,$geteventNameSql);
		$geteventNameRow = mysqli_fetch_array($geteventName);
		$eventName = $geteventNameRow['eventName'];
		$rows = mysqli_fetch_array($getEventData);
			$mark=explode(',', $rows['eventdataImage1']);//what will do here
			foreach($mark as $out) {
		echo "
			<tr>
				<td>$eventdataId</td>
				<td>$eventName</td>
				<td><img src='resources/event_img/$out' style='width: 50px;height:50px;'></td>
				"; }  echo"
				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteEventData=$eventdataId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>			
				<td><a href='index.php?editeventdata=$eventdataId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";
	}
}
function updateEventData(){
	
	global $connF;
	
	if(isset($_POST['updateeventdata'])){
		
		$eventdataId = $_GET['editeventdata'];
		
		$getEventDataSql = "SELECT * FROM eventdata WHERE eventdataId='$eventdataId'";
		$getEventData = mysqli_query($connF,$getEventDataSql);
		$getEventDataRow = mysqli_fetch_array($getEventData);
		
		$eventdataImageOld1 = $getEventDataRow['eventdataImage1'];
		$eventdataImageOld2 = $getEventDataRow['eventdataImage2'];
		$eventdataImageOld3 = $getEventDataRow['eventdataImage3'];

		$eventdata = $_POST['eventdata'];
		$eventdataImage1 = $_FILES['eventdataImage1']['name'];
		$eventdataImage2 = $_FILES['eventdataImage2']['name'];
		$eventdataImage3 = $_FILES['eventdataImage3']['name'];

		$EventId = $_POST['eventId'];
	
		if(empty($eventdataImage1)){
			$eventdataImage1 = $eventdataImageOld1;
		}
		if(empty($eventdataImage2)){
			$eventdataImage2 = $eventdataImageOld2;
		}
		if(empty($eventdataImage3)){
			$eventdataImage3 = $eventdataImageOld3;
		}
		$tempImg1 = $_FILES['eventdataImage1']['tmp_name'];
		$tempImg2 = $_FILES['eventdataImage2']['tmp_name'];
		$tempImg3 = $_FILES['eventdataImage3']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/event_img/$eventdataImage1");
		move_uploaded_file($tempImg2,"resources/event_img/$eventdataImage2");
		move_uploaded_file($tempImg3,"resources/event_img/$eventdataImage3");


$updateEventDataSql = "UPDATE eventdata SET eventId='$EventId',eventdataImage1='$eventdataImage1',eventdataImage2='$eventdataImage2',eventdataImage3='$eventdataImage3' WHERE eventdataId='$eventdataId'";
		$updateEventData = mysqli_query($connF,$updateEventDataSql);
		if($updateEventData){
			echo "<script>alert('Sub Service Updated')</script>";
			echo "<script>window.open('index.php?addeventdata','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addeventdata','_self')</script>";
		}
	}
	}

function deleteEventData(){
	global $connF;
	if(isset($_GET['deleteEventData'])){
		
		$eventdataId = $_GET['deleteEventData'];
		$deleteEventDataSql = "DELETE FROM  eventdata WHERE eventdataId='$eventdataId'";
		$deleteEventData = mysqli_query($connF,$deleteEventDataSql);
		if($deleteEventData){
			echo "<script>window.open('index.php?addeventdata','_self')</script>";
		}
	}
	
}


// CLIENTS

function addClient(){
	global $connF;
	if(isset($_POST['addnewclient'])){
		
		$clientName = $_POST['clientName'];
		$clientImage = $_FILES['clientImage']['name'];
		$tempImg1 = $_FILES['clientImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/client_img/$clientImage");
		$addClientSql = "INSERT INTO clients(clientName,clientImage) VALUES ('$clientName','$clientImage')";
		$addClient = mysqli_query($connF,$addClientSql);
		if($addClient){
			echo "<script>alert('Client Added')</script>";
			echo "<script>window.open('index.php?addclient','_self')</script>";
		}
		
	}
}





function displayClient(){
	global $connF;
	$getClientSql = "SELECT * FROM clients WHERE 1";
	$getClient = mysqli_query($connF,$getClientSql);
	while($getClientRow = mysqli_fetch_array($getClient)){
		$clientId = $getClientRow['clientId'];
		$clientName = $getClientRow['clientName'];
		$clientImage = $getClientRow['clientImage'];
		echo "
			<tr>
				<td>$clientId</td>
				<td>$clientName</td>
				<td><img src='resources/client_img/$clientImage' style='width: 50px;height:50px;'></td>
                <td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteClient=$clientId'class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
                <td><a href='index.php?editclient=$clientId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";

	}
}
function updateClient(){
	
	global $connF;
	
	if(isset($_POST['updateclient'])){
		
		$clientId = $_GET['editclient'];
		
		$getClientSql = "SELECT * FROM clients WHERE clientId='$clientId'";
		$getClient = mysqli_query($connF,$getClientSql);
		$getClientRow = mysqli_fetch_array($getClient);
		
		$clientImageOld = $getClientRow['clientImage'];
		$clientName = $_POST['clientName'];
		$clientImage = $_FILES['clientImage']['name'];
		
		if(empty($clientImage)){
			$clientImage = $clientImageOld;
		}
	
		$tempImg1 = $_FILES['clientImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/client_img/$clientImage");
		// if(!empty($clientImageOld)){
		// 	unlink("resources/client_img/$clientImage");
		// }

        $updateClientSql = "UPDATE clients SET clientName='$clientName',clientImage='$clientImage' WHERE clientId='$clientId'";
		$updateClient = mysqli_query($connF,$updateClientSql);
		if($updateClient){
			echo "<script>alert('Client Updated')</script>";
			echo "<script>window.open('index.php?addclient','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addclient','_self')</script>";
		}
	    }
	}

function deleteClient(){
	global $connF;
	if(isset($_GET['deleteClient'])){
		
		$ClientId = $_GET['deleteClient'];
		$deleteClientSql = "DELETE FROM clients WHERE clientId='$ClientId'";
		$deleteClient = mysqli_query($connF,$deleteClientSql);
		if($deleteClient){
			echo "<script>window.open('index.php?addclient','_self')</script>";
		}
	}
	
}
//SUB CLIENT


function addSubClient(){
	global $connF;
	if(isset($_POST['addnewsubclient'])){
		
		$subclient = $_POST['subclient'];
		$ClientId = $_POST['clientId'];
		$subclientImage = $_FILES['subclientImage']['name'];
		$tempImg1 = $_FILES['subclientImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/subclient_img/$subclientImage");

		$addSubClientSql = "INSERT INTO subclient(subclient,clientId,subclientImage) VALUES ('$subclient','$ClientId','$subclientImage')";
		$addSubClient = mysqli_query($connF,$addSubClientSql);
		if($addSubClient){
			echo "<script>alert('Sub Client Added')</script>";
			echo "<script>window.open('index.php?addsubclient','_self')</script>";
		}
		
	}
}


function displaySubClient(){
	global $connF;
	$getSubClientSql = "SELECT * FROM subclient WHERE 1";
	$getSubClient = mysqli_query($connF,$getSubClientSql);
	while($getSubClientRow = mysqli_fetch_array($getSubClient)){
		$subclientId = $getSubClientRow['subclientId'];
		$subclient = $getSubClientRow['subclient'];
		$subclientImage = $getSubClientRow['subclientImage'];
		$ClientId = $getSubClientRow['clientId'];
		// $clientImage = $getCategoryRow['clientImage'];
		$getclientNameSql = "SELECT * FROM clients WHERE clientId='$ClientId'";
		$getclientName = mysqli_query($connF,$getclientNameSql);
		$getclientNameRow = mysqli_fetch_array($getclientName);
		$clientName = $getclientNameRow['clientName'];
		echo "
			<tr>
				<td>$subclientId</td>
				<td>$clientName</td>
				<td>$subclient</td>
				<td><img src='resources/subclient_img/$subclientImage' style='width: 50px;height:50px;'></td>

				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteSubClient=$subclientId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>			
				<td><a href='index.php?editsubclient=$subclientId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";
	}
}
function updateSubClient(){
	
	global $connF;
	
	if(isset($_POST['updatesubclient'])){
		
		$subclientId = $_GET['editsubclient'];
		
		$getSubClientSql = "SELECT * FROM subclient WHERE subclientId='$subclientId'";
		$getSubClient = mysqli_query($connF,$getSubClientSql);
		$getSubClientRow = mysqli_fetch_array($getSubClient);
		
		$subclientImageOld1 = $getSubClientRow['subclientImage'];
		
		$subclient = $_POST['subclient'];
		$subclientImage = $_FILES['subclientImage']['name'];
	
		$ClientId = $_POST['clientId'];
	
		if(empty($subclientImage)){
			$subclientImage = $subclientImageOld1;
		}
	
		$tempImg1 = $_FILES['subclientImage']['tmp_name'];
		
		move_uploaded_file($tempImg1,"resources/subclient_img/$subclientImage");
		

$updateSubClientSql = "UPDATE subclient SET subclient='$subclient',clientId='$ClientId',subclientImage='$subclientImage' WHERE subclientId='$subclientId'";
		$updateSubClient = mysqli_query($connF,$updateSubClientSql);
		if($updateSubClient){
			echo "<script>alert('Sub Client Updated')</script>";
			echo "<script>window.open('index.php?addsubclient','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?addsubclient','_self')</script>";
		}
	}
	}

function deleteSubClient(){
	global $connF;
	if(isset($_GET['deleteSubClient'])){
		
		$subclientId = $_GET['deleteSubClient'];
		$deleteSubClientSql = "DELETE FROM  subclient WHERE subclientId='$subclientId'";
		$deleteSubClient = mysqli_query($connF,$deleteSubClientSql);
		if($deleteSubClient){
			echo "<script>window.open('index.php?addsubclient','_self')</script>";
		}
	}
	
}


//
function addDirector(){
	global $connF;
	if(isset($_POST['addnewdirector'])){
	    
	    
		$directorImage = $_FILES['directorImage']['name'];
		$tempImg1 = $_FILES['directorImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/director_img/$directorImage");

        $directorheaderImage = $_FILES['directorheaderImage']['name'];
		$tempImg2 = $_FILES['directorheaderImage']['tmp_name'];
		move_uploaded_file($tempImg2,"resources/director_img/$directorheaderImage");

        $mdirectorImage = $_FILES['mdirectorImage']['name'];
		$tempImg3 = $_FILES['mdirectorImage']['tmp_name'];
		move_uploaded_file($tempImg3,"resources/director_img/$mdirectorImage"); 

		$mdirectorheaderImage = $_FILES['mdirectorheaderImage']['name'];
		$tempImg4 = $_FILES['mdirectorheaderImage']['tmp_name'];
		move_uploaded_file($tempImg4,"resources/director_img/$mdirectorheaderImage"); 
		
		$hodheaderImage = $_FILES['hodheaderImage']['name'];
		$tempImg5 = $_FILES['hodheaderImage']['tmp_name'];
		move_uploaded_file($tempImg5,"resources/director_img/$hodheaderImage"); 
		
		$expertheaderImage = $_FILES['expertheaderImage']['name'];
		$tempImg6 = $_FILES['expertheaderImage']['tmp_name'];
		move_uploaded_file($tempImg6,"resources/director_img/$expertheaderImage"); 
		
		$resourceheaderImage = $_FILES['resourceheaderImage']['name'];
		$tempImg7 = $_FILES['resourceheaderImage']['tmp_name'];
		move_uploaded_file($tempImg7,"resources/director_img/$resourceheaderImage"); 
		$directorheaderTxt= $_POST['directorheaderTxt'];
	    $mdirectorheaderTxt= $_POST['mdirectorheaderTxt'];
	    $hodheaderTxt= $_POST['hodheaderTxt'];
	    $expertheaderTxt= $_POST['expertheaderTxt'];
	    $resourceheaderTxt= $_POST['resourceheaderTxt'];

		$addDirectorSql = "INSERT INTO director(directorImage,directorheaderImage,mdirectorImage,mdirectorheaderImage,hodheaderImage,expertheaderImage,resourceheaderImage,directorheaderTxt,mdirectorheaderTxt,hodheaderTxt,expertheaderTxt,resourceheaderTxt) VALUES ('$directorImage','$directorheaderImage','$mdirectorImage','$mdirectorheaderImage','$hodheaderImage','$expertheaderImage','$resourceheaderImage','$directorheaderTxt','$mdirectorheaderTxt','$hodheaderTxt','$expertheaderTxt','$resourceheaderTxt')";
		$addDirector = mysqli_query($connF,$addDirectorSql);
		if($addDirector){
			echo "<script>alert('Sub Service Added')</script>";
			echo "<script>window.open('index.php?adddirector','_self')</script>";
		}
		
	}
}


function displayDirector(){
	global $connF;
	$getDirectorSql = "SELECT * FROM director WHERE 1";
	$getDirector = mysqli_query($connF,$getDirectorSql);
	while($getDirectorRow = mysqli_fetch_array($getDirector)){
		$directorId = $getDirectorRow['directorId'];
		
		$directorImage = $getDirectorRow['directorImage'];
        $directorheaderImage = $getDirectorRow['directorheaderImage'];
        $mdirectorImage = $getDirectorRow['mdirectorImage'];
        $mdirectorheaderImage = $getDirectorRow['mdirectorheaderImage'];
		echo "
			<tr>
				<td>$directorId</td>
				<td><img src='resources/director_img/$directorImage' style='width: 50px;height:50px;'></td>
				<td><img src='resources/director_img/$directorheaderImage' style='width: 50px;height:50px;'></td>
				<td><img src='resources/director_img/$mdirectorImage' style='width: 50px;height:50px;'></td>
				<td><img src='resources/director_img/$mdirectorheaderImage' style='width: 50px;height:50px;'></td>

				<td><a onClick=\"javascript: return confirm('Please confirm deletion');\" href='index.php?deleteDirector=$directorId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>			
				<td><a href='index.php?editdirector=$directorId' class='btn btn-sm btn-circle btn-warning delete_product'><i class='fa fa-edit'></i></a></td>

			</tr>
		
		";
	}
}
function updateDirector(){
	

	global $connF;
	
	if(isset($_POST['updatedirector'])){
		
		$directorId = $_GET['editdirector'];
		
		$getDirectorSql = "SELECT * FROM director WHERE directorId='$directorId'";
		$getDirector = mysqli_query($connF,$getDirectorSql);
		$getDirectorRow = mysqli_fetch_array($getDirector);
	
		    $directorheaderTxt= $_POST['directorheaderTxt'];
	    $mdirectorheaderTxt= $_POST['mdirectorheaderTxt'];
	    $hodheaderTxt= $_POST['hodheaderTxt'];
	    $expertheaderTxt= $_POST['expertheaderTxt'];
	    $resourceheaderTxt= $_POST['resourceheaderTxt'];
		$directorImageOld1 = $getDirectorRow['directorImage'];
		$directorImageOld2 = $getDirectorRow['directorheaderImage'];
		$directorImageOld3 = $getDirectorRow['mdirectorImage'];
		$directorImageOld4 = $getDirectorRow['mdirectorheaderImage'];
		$directorImageOld5 = $getDirectorRow['hodheaderImage'];
    	$directorImageOld6 = $getDirectorRow['expertheaderImage'];
	    $directorImageOld7 = $getDirectorRow['resourceheaderImage'];
		$directorImage = $_FILES['directorImage']['name'];
		$directorheaderImage = $_FILES['directorheaderImage']['name'];
		$mdirectorImage = $_FILES['mdirectorImage']['name'];
		$mdirectorheaderImage = $_FILES['mdirectorheaderImage']['name'];
        $hodheaderImage = $_FILES['hodheaderImage']['name'];
	    $expertheaderImage = $_FILES['expertheaderImage']['name'];
        $resourceheaderImage = $_FILES['resourceheaderImage']['name'];
		if(empty($directorImage)){
			$directorImage = $directorImageOld1;
		}
		if(empty($directorheaderImage)){
			$directorheaderImage = $directorImageOld2;
		}
		if(empty($mdirectorImage)){
			$mdirectorImage = $directorImageOld3;
		}
        if(empty($mdirectorheaderImage)){
			$mdirectorheaderImage = $directorImageOld4;
		}
		 if(empty($hodheaderImage)){
			$hodheaderImage = $directorImageOld5;
		}
		 if(empty($expertheaderImage)){
			$expertheaderImage = $directorImageOld6;
		}
		 if(empty($resourceheaderImage)){
			$resourceheaderImage = $directorImageOld7;
		}
		$tempImg1 = $_FILES['directorImage']['tmp_name'];
		$tempImg2 = $_FILES['directorheaderImage']['tmp_name'];
		$tempImg3 = $_FILES['mdirectorImage']['tmp_name'];
		$tempImg4 = $_FILES['mdirectorheaderImage']['tmp_name'];
		$tempImg5 = $_FILES['hodheaderImage']['tmp_name'];
		$tempImg6 = $_FILES['expertheaderImage']['tmp_name'];
		$tempImg7 = $_FILES['resourceheaderImage']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/director_img/$directorImage");
		move_uploaded_file($tempImg2,"resources/director_img/$directorheaderImage");
		move_uploaded_file($tempImg3,"resources/director_img/$mdirectorImage");
		move_uploaded_file($tempImg4,"resources/director_img/$mdirectorheaderImage");
        move_uploaded_file($tempImg5,"resources/director_img/$hodheaderImage");
        move_uploaded_file($tempImg6,"resources/director_img/$expertheaderImage");
        move_uploaded_file($tempImg7,"resources/director_img/$resourceheaderImage");

$updateDirectorSql = "UPDATE director SET directorImage='$directorImage',directorheaderImage='$directorheaderImage',mdirectorImage='$mdirectorImage',mdirectorheaderImage='$mdirectorheaderImage',directorheaderTxt='$directorheaderTxt',mdirectorheaderTxt='$mdirectorheaderTxt',hodheaderTxt='$hodheaderTxt',expertheaderTxt='$expertheaderTxt',resourceheaderTxt='$resourceheaderTxt',hodheaderImage='$hodheaderImage',expertheaderImage='$expertheaderImage',resourceheaderImage='$resourceheaderImage' WHERE directorId='$directorId'";
		$updateDirector = mysqli_query($connF,$updateDirectorSql);
		if($updateDirector){
			echo "<script>alert('Sub Service Updated')</script>";
			echo "<script>window.open('index.php?adddirector','_self')</script>";
		}
		else{
			echo "<script>alert('Something Wrong!')</script>";
			echo "<script>window.open('index.php?adddirector','_self')</script>";
		}
	}
	}

function deleteDirector(){
	global $connF;
	if(isset($_GET['deleteSubService'])){
		
		$directorId = $_GET['deleteSubService'];
		$deleteSubServiceSql = "DELETE FROM  director WHERE directorId='$directorId'";
		$deleteSubService = mysqli_query($connF,$deleteSubServiceSql);
		if($deleteSubService){
			echo "<script>window.open('index.php?adddirector','_self')</script>";
		}
	}
	
}
function addNewAds(){
	global $connF;
	if(isset($_POST['addnewad'])){
		
		$adTitle = $_POST['adname'];
		$adDetail = $_POST['addetail'];
		$addNewAdSql = "INSERT INTO adds(addTitle,addDescription) VALUES ('$adTitle','$adDetail')";
		$addNewAd = mysqli_query($connF,$addNewAdSql);
		if($addNewAd){
			echo "<script>alert('Ad Added')</script>";
			echo "<script>window.open('index.php?addads','_self')</script>";
		}
	}
}
 
function viewAds(){
	global $connF;
	if(isset($_GET['viewads'])){
		$getAdSql = "SELECT * FROM adds WHERE 1";
		$getAd = mysqli_query($connF,$getAdSql);
		while($getAdRow = mysqli_fetch_array($getAd)){
			$adId = $getAdRow['addId'];
			$adTitle = $getAdRow['addTitle'];
			$adDetail = $getAdRow['addDescription'];
			echo "
				<tr>
					<td>$adId</td>
					<td>$adTitle</td>
					<td>$adDetail</td>
					<td><a href='index.php?deleteAd=$adId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
				</tr>
			";
		}
	}
	
}

function deleteAds(){
	global $connF;
	if(isset($_GET['deleteAd'])){
		$adId = $_GET['deleteAd'];
		$deleteAdSql = "DELETE FROM adds WHERE addId='$adId'";
		$deleteAd = mysqli_query($connF,$deleteAdSql);
		if($deleteAd){
			echo "<script>window.open('index.php?viewads','_sel
			f')</script>";
		}
	}
}
 
function displayAds(){
	global $connF;
	$getAdsSql = "SELECT * FROM adds ORDER BY addId LIMIT 3";
	$getAds = mysqli_query($connF,$getAdsSql);
	while($getAdsRow = mysqli_fetch_array($getAds)){
		$adTitle = $getAdsRow['addTitle'];
		$adDetail = $getAdsRow['addDescription'];
		echo "
			<div class='col-sm-4'>
					<div class='box same-height'>
						<h3><a href='#'>$adTitle</a></h3>
						<p>$adDetail</p>
					</div>
				</div>
		
			";
		
	}
}

function addSlide(){
	global $connF;
	if(isset($_POST['addnewslide'])){
		
		// $slideName = $_POST['slidename'];
		$slideName = htmlentities($_POST['slidename']);
		$slideImg = $_FILES['slideimg']['name'];
		$tempImg1 = $_FILES['slideimg']['tmp_name'];
		move_uploaded_file($tempImg1,"resources/slideshow/$slideImg");
		$slideDesc = $_POST['slidedescription'];
		$addNewSlideSql = "INSERT INTO slider(sName, sImage, sDesc) VALUES ('$slideName','$slideImg','$slideDesc')";
		$addNewSlide = mysqli_query($connF,$addNewSlideSql);
		if($addNewSlide){
			echo "<script>alert('Slide Added')</script>";
			echo "<script>window.open('index.php?addslideshow','_self')</script>";
		}
	}
}

function viewSlide(){
	global $connF;
	$getSlidesSql = "SELECT * FROM slider WHERE 1";
	$getSlides = mysqli_query($connF,$getSlidesSql);
	while($getSlidesRow = mysqli_fetch_array($getSlides)){
		$slideId = $getSlidesRow['sliderId'];
		$slideName = $getSlidesRow['sName'];
		$slideImg = $getSlidesRow['sImage'];
		echo "	
				<tr>
					<td>$slideId</td>
					<td>$slideName</td>
					<td><img src='resources/slideshow/$slideImg' style='width: 50px;height:50px;'></td>
					<td><a href='index.php?deleteSlide=$slideId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
				</tr>
		
			";
	}
}

function deleteSlide(){
	global $connF;
	if(isset($_GET['deleteSlide'])){
		$slideId = $_GET['deleteSlide'];
		$deleteSlideSql = "DELETE FROM slider WHERE sliderId='$slideId'";
		$deleteSlide = mysqli_query($connF,$deleteSlideSql);
		if($deleteSlide){
			echo"<script>alert('Slide Deleted')</script>";
			echo "<script>window.open('index.php?addslideshow','_self')</script>";
		}
	}
}

function addNewAdmin(){
	global $connF;
	if(isset($_POST['addnewadmin'])){
		$adminName = $_POST['adminName'];
		$adminEmail = $_POST['adminEmail'];
		$adminPass = $_POST['adminPass'];
		$adminCPass = $_POST['adminCPass'];
		$adminImg = $_FILES['adminimg1']['name'];
		$adminTempImg = $_FILES['adminimg1']['tmp_name'];
		$adminPno = $_POST['adminPNo'];
		
		if($adminPass == $adminCPass){
			$adminPassEnc = md5($adminPass);
			$addAdminSql = "INSERT INTO admin(adminName, adminEmail, adminPassword, adminPhoto, adminPNum) VALUES ('$adminName','$adminEmail','$adminPassEnc','$adminImg','$adminPno')";
			$addAdmin = mysqli_query($connF,$addAdminSql);
			move_uploaded_file($adminTempImg,"resources/admin_img/$adminImg");
			if($addAdmin){
			echo "<script>alert('Admin Added')</script>";
			echo "<script>window.open('index.php?addadmin','_self')</script>";
		}
		}
	}
}

function viewAdmin(){
	global $connF;
	$viewAdminSql ="SELECT * FROM admin WHERE 1";
	$viewAdmin = mysqli_query($connF,$viewAdminSql);
	
	while($viewAdminRow = mysqli_fetch_array($viewAdmin)){
		$adminId = $viewAdminRow['adminId'];
		$adminName = $viewAdminRow['adminName'];
		$adminEmail = $viewAdminRow['adminEmail'];
		$adminPass = $viewAdminRow['adminPassword'];
		$adminPassDec = md5($adminPass);
		$adminImg = $viewAdminRow['adminPhoto'];
		$adminPno = $viewAdminRow['adminPNum'];
		
		echo "	
				<tr>
					<td>$adminId</td>
					<td>$adminName</td>
					<td>$adminEmail</td>
					<td>$adminPassDec</td>
					<td><img src='resources/admin_img/$adminImg' style='width: 50px;height:50px;'></td>
					<td>$adminPno</td>
					<td><a href='index.php?deleteAdmin=$adminId' class='btn btn-sm btn-circle btn-danger delete_product'><i class='fa fa-trash'></i></a></td>
				</tr>
		
			";
	}
}

function deleteAdmin(){
	global $connF;
	if(isset($_GET['deleteAdmin'])){
		$adminId = $_GET['deleteAdmin'];
		$deleteAdminSql = "DELETE FROM admin WHERE adminId='$adminId'";
		$deleteAdmin = mysqli_query($connF,$deleteAdminSql);
		if($deleteAdmin){
			echo"<script>alert('Admin Deleted')</script>";
			echo "<script>window.open('index.php?addadmin','_self')</script>";
		}
	}
}

function contactUs(){
	global $connF;
	if(isset($_POST['contactus'])){
		$department = $_POST['department'];
		$cusName = $_POST['name'];
		$cusEmail = $_POST['email'];
		$subject = $_POST['subject'];
		$message = $_POST['message'];
		
		$saveInqueySql ="INSERT INTO supportticket(ticketDepartment, ticketcusName, ticketcusEmail, ticketcusSub, ticketcusMsg) VALUES ('$department','$cusName','$cusEmail','$subject','$message')";
		$saveInquey = mysqli_query($connF,$saveInqueySql);
		$supportEmail = 'mailer.nilkamal@gmail.com';
		
		//PHPMailer Function
			$mail = new PHPMailer;
			$mail->isSMTP();
			$mail->SMTPDebug = 0;
			$mail->Debugoutput = 'html';
			$mail->Host = 'smtp.gmail.com';
			$mail->Port = 587;
			$mail->SMTPSecure = 'tls';
			$mail->SMTPAuth = true;
			$mail->Username = "mailer.nilkamal@gmail.com";
			$mail->Password = "nilkamal@123456";
			$mail->setFrom('mailer.nilkamal@gmail.com', 'nilkamal Support');
			$mail->addAddress($supportEmail, 'Inquery Handler');
			$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
			$mail->Subject = 'Customer Inquery - nilkamal';
			$mail->Body = "
						<b> Department : $department </b>
						<br><br>
						<b> Customer Name : $cusName </b>
						<br><br>
						<b> Customer Email : $cusEmail </b>
						<br><br>
						<b> Subject : $subject </b>
						<br><br>
						<p> Message : $message </p>
						<br><br>
						<br><br>
						<b><i>If you need any kind of assistant, please contact Root Administrator</i></b>
						";
			if (!$mail->send()) {
				echo"<script>alert('Something Wrong, Please Call Us')</script>";
			} 
			else {
				echo"<script>alert('Inquery has been sent, Our customer service will contact you')</script>";
			}
	}
}


function returnCustomerId(){
	global $connF;
	$customerEmail = $_SESSION['cusEmail'];	
	$getCustomerIdSql = "SELECT * FROM customer WHERE cusEmail='$customerEmail'";
	$getCustomerId = mysqli_query($connF,$getCustomerIdSql);
	$getCustomerIdRow = mysqli_fetch_array($getCustomerId);
	$customerId = $getCustomerIdRow['cusId'];

	return $customerId;

}

?>
